### ISSUE TITLE
Neumes can be placed on top of each other

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon#233]
This is not an important issue, more of an optimization. Right now, users can put two nc's in the exact same place (stacked on top of each other). Neon should by default place it to the left or the right of the nc to avoid errors.

**Comment by JRegimbal** [comment]
Is this about dragging or inserting or both?

**Comment by zoemcl** [comment]
@JRegimbal For dragging they can be layered. As for insert, if you try to insert on top of another element, nothing happens (no insert, no fail message) , which is also an issue.

**Comment by jacob-hutnyk** [comment]
Because this is font specific, we won't/can't fix it
