### ISSUE TITLE
Modularize Neon

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#341]
Modularize Neon so that it works with diva.js while not entirely supplanting the original container view.
NeonView and NeonCore should be common to all instances of Neon, with the following modules being used with a common API (to be defined):

* [x] View - Handles rendering the SVG over the image. Manages changes in opacity/zoom/panning/etc. Must be able to request an SVG using a page number (0 for single page views), and subscribe to notices from NeonView that an SVG (for a page) has changed. Must notify NeonView (and thus other modules) when an SVG changes.
* [x] DisplayPanel - UI component allowing the user to tweak how the rendered image appears. Can directly work on the DOM but must be told where to look by the View. Interactions are NOT page specific.
* [x] InfoModule - Adds event handlers to the current page of the View and makes queries to NeonView. Also has control of a dedicated UI component.
* [x] EditMode - Optional. Adds event handlers to the current page of the View and sends actions to NeonView. These actions result in changes to the MEI file and possibly a new SVG, which is then pushed to NeonView. When the SVG is rendered/refreshed by the View, the EditMode must reset its handlers to apply to the current page. Also has control of a dedicated UI component (currently would be the Insert and Edit panels).
* [x] TextView - Optional. Module for displaying (and possibly editing) syllable text. (Closed in #348)

This may also involve making NeonCore (and thus Verovio) into a webworker that handles database calls and caching. This will prevent calls to Verovio from slowing down the rest of the application (especially when parsing MEI files) and allow communication through message passing.

**Comment by JRegimbal** [comment]
@vigliensoni Do you have any feedback on these general ideas for modularizing Neon?

**Comment by vigliensoni** [comment]
I think this is a fairly good summary of the discussion. Having the functionality separated into different modules will also help in providing additional features. For example, working on the compensation for slanted staff lines will benefit of this modularization.

You mention EditMode as optional. Is there any reason for this?

**Comment by JRegimbal** [comment]
We've wanted the viewer as optional in the past and since it's modular it wouldn't be too hard to support compiling Neon without editor capabilities.

**Comment by JRegimbal** [comment]
Now that I think about it more, it would also make sense to have a separate TextView that manages displaying the syllable text.

**Comment by vigliensoni** [comment]
That makes lots of sense. So, are we thinking about two different views: NeumeView and TextView? If so, I guess we would need a different EditMode.

**Comment by JRegimbal** [comment]
I suppose. Currently it's named `View` and `TextView` but that can be changed easily. Having a separate edit module for text view would make sense...it's possible we could have that built into the same `TextView` module and just wait until the rest of Neon goes into edit mode to make that functionality available. Since we really don't have much in the lines of text viewing or editing at this point I feel like we have a lot of flexibility here.
