### ISSUE TITLE
text and syl editing

### ISSUE THREAD

**Issue by jacob-hutnyk** [DDMAL/Neon#356]
implement editing the text and bounding boxes of syllables, all done in a modular way so that it works with single page view and with diva view

- [x] first complete DDMAL/Neon2#362 so that implementing these features is easy and modular
- [x] modify text contents by clicking on the text in the bottom right
- [x] modify position of bounding box by clicking the center and dragging
- [x] modify size of bounding box by clicking edges and dragging
- [x] make sure that every syllable gets a boundingbox when it is created, whether by ungrouping or in the io
- [x] ensure that when grouping/ungrouping features also modify the bounding boxes
- [x] have the bounding box be highlighted when a syllable/neume/nc is selected
- [x] have the bounding boxes be coloured like their syllable when using the highlight feature

**Comment by jacob-hutnyk** [comment]
After reading through @JRegimbal's code in #343 it looks like it actually might be easier to have all of these features included in UnifiedEdit rather than having TextEdit be a separate module:

- Text editing is already implemented in UnifiedEdit
- Selecting Syllables and Neumes should also highlight their text bounding boxes, and so the code for highlighting selected stuff is already in UnifiedEdit. Changing it to also highlight the text bounding boxes would be a very small fix.
- Dragging and resizing logic is also already implemented in UnifiedEdit, and extending it to work with text bounding boxes would be relatively simple

**Comment by JRegimbal** [comment]
We may eventually support different neume notation types than square-notation where the editing features will need to be slightly different. Because of this it makes sense to separate out text editing functionality since that would remain the same across neume notations.
