### ISSUE TITLE
Infobox should be activated/deactivated with Display info button

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Neon#428]
With the current behavior, Infobox is only triggered only when the user hovers over a neume, even if the "Display info" toggle is activated.

**Comment by JRegimbal** [comment]
@vigliensoni Could you clarify what you mean by this? It is unclear what the desired behavior is.

**Comment by jacob-hutnyk** [comment]
In the [428](https://github.com/DDMAL/Neon/tree/428) branch I have made some changes to the infoModule so that the Infobox is always displaying something when the checkbox is checked, and so that it is always updating. Please take a look @vigliensoni
