### ISSUE TITLE
change neon test file

### ISSUE THREAD

**Issue by jacob-hutnyk** [DDMAL/Neon#465]
The current mei file used for testing in NeonCore and SinglePageBrowser has neumes as having facsimile data, instead of nc as it should be, as well as some other small quirks/problems. This limits our ability to test certain editor actions

**Comment by JRegimbal** [comment]
The current file seems to be an old encoding of Folio 011r in the Salzinnes Antiphonal. It would probably be easiest to update to a newer encoding of this page rather than start from scratch.
