### ISSUE TITLE
Add webpack to installation instructions

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Neon#533]

**Comment by JRegimbal** [comment]
Could you clarify this a bit? The second step of the installation instructions (`yarn build`) is what triggers the webpack build.

**Comment by vigliensoni** [comment]
Was not enough in my case on macOS. I had to install webpack (i.e., `brew install webpack`, `yarn add webpack --dev`).

**Comment by JRegimbal** [comment]
That's strange. Webpack should be installed as part of the previous (`yarn install`) step.

**Comment by JoyfulGen** [comment]
@yinanazhou what about this one?

**Comment by jinh0** [comment]
I can confirm this is no longer an issue.
