### ISSUE TITLE
Create a Favicon for Neon

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#542]
Currently Neon lacks a Favicon, meaning when it is loaded there is no icon associated with it. E.g. A tab with Neon loaded will just say "Neon" and lack an icon next to it.

One should be created and used on the development and GitHub pages servers.

**Comment by JRegimbal** [comment]
I'd like to note that I already do have a favicon of my cat. Just in case.
![favicon](https://user-images.githubusercontent.com/6963142/63463996-4d89ea80-c42c-11e9-94aa-c293055cbad9.jpg)

**Comment by JRegimbal** [comment]
On a more serious note [this link](https://github.com/audreyr/favicon-cheat-sheet) seems like it'll be helpful to whoever handles this.

**Comment by annamorphism** [comment]
just a note that there seem to be different favicons for the landing page and editing pages right now. 
![image](https://user-images.githubusercontent.com/67451875/182183807-808355c2-71a8-4fde-9267-da506b886381.png)

**Comment by yinanazhou** [comment]
@annamorphism could you please confirm that this issue is fixed now?

**Comment by annamorphism** [comment]
Looks that way! Closing.
