### ISSUE TITLE
staff selection problems

### ISSUE THREAD

**Issue by jacob-hutnyk** [DDMAL/Neon#570]
after merging two staves the resulting staff can't be unselected without clicking esc or selecting another staff, even once unselected the highlighting is buggy

**Comment by jacob-hutnyk** [comment]
this occurs when you click within the svg bounding box of a staff while it is selected, and can occur with any staff not just recently merged ones. staves which have a large skew tend to have very large svg bounding boxes, as do those which contain the staff def clef

**Comment by jacob-hutnyk** [comment]
a potential solution to this (that would also improve staff selection in general) is to insert an invisible 'staff' polygon that matches the path elements of the staff. when that element (or any of the other staff children like neumes) is clicked on, the staff is selected.

this would also resolve the problem of selecting staves: you can't click the space between staff lines, and selecting staves by clicking on the path elements is pretty buggy.

**Comment by jacob-hutnyk** [comment]
ok actually a much easier way is just to fix the filter statement in Select.ts:
`const selectedStaves = Array.from(document.getElementsByClassName('staff'))
      .filter((staff: SVGGElement) => {
        const bbox = getStaffBBox(staff);
        return (bbox.ulx < pt.x && pt.x < bbox.lrx) && (bbox.uly < pt.y && pt.y < bbox.lry);
      });`

this should check whether the point is actually inside the staff not just whether it's in the staff bbox

**Comment by JRegimbal** [comment]
@jacob-hutnyk That seems better. I'd recommend taking some of the logic from determining skew using the paths to get the four corner points of the staff and the skew.
