### ISSUE TITLE
[develop] Overfull context menu has dropdown placed below buttons

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#579]
Specifically for the clef context menu, but could apply to any. The overflow settings cause the dropdown menu for clef shape to appear *under* the button to reassociate to nearest staff. The user has to scroll within this context menu box to get to the dropdown menu.
![Screenshot_2019-09-19 Neon](https://user-images.githubusercontent.com/6963142/65264662-1830f500-dadd-11e9-856f-1ecd17f80668.png)
The issue is caused by `overflow: auto;` on `#moreEdit`.

**Comment by JRegimbal** [comment]
Note that the default size of the `#moreEdit` box is too small to see everything without scrolling. I manually increased the height of the box to see everything for the purpose of taking a screenshot.

**Comment by jacob-hutnyk** [comment]
After looking into this a bit, it seems like having dropdowns inside of elements which need to overflow is a pretty general problem without a great solution. Potentially we could put the clef dropdown as something separate from the '#moreEdit' div, although this would require more substantial changes then just changing the HTML
