### ISSUE TITLE
Zoom hotkeys do not work properly on Macs

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#583]
`Cmd`+`+` and `Cmd`+`-` do not work for zooming on Macs. However replacing `Cmd` with `Ctrl` does. It's possible we should have other controls for zooming that will not conflict with common browser/OS level hotkeys.

**Comment by caitlin-hutnyk** [comment]
On single-view mode both Cmd + and Ctrl + are working for me on safari, chrome, and firefox. And I don't think we ever supported hotkey zooming on diva mode. Can anyone else reproduce this issue?

**Comment by JRegimbal** [comment]
Perhaps just using `+` and `-` as the hotkeys would work? I believe Inkscape does the same thing.

**Comment by caitlin-hutnyk** [comment]
working fine, updated wiki
