### ISSUE TITLE
MEI staff and sb converter does not work for all valid MEI files

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#589]
The converter written to go back and forth between staff- and sb-based MEI files made a few assumptions about the structure of provided MEI files using the MEI guidelines. However some currently-allowed structures were not accounted for by the current converter. Element positions allowed by the converter, with new positions in brackets, are:

* `sb` in `layer` with one appearing at the very start*
* `clef` in `layer` [or `syllable`]
* `sb` in `layer` or `syllable`
* `custos` in `layer` or `sb` [or `syllable`]
* `clef` in `layer` [or `syllable`]

\*This is not a requirement of MEI but a requirement to get the position of the first staff element once converted.

**Comment by JRegimbal** [comment]
Changing severity since this is now a bottleneck in the workflow.

**Comment by JRegimbal** [comment]
Verovio has been updated. This does NOT fix this issue but is a significant step towards it. Rewriting script to convert this. It cannot be one-to-one since there is no "good" way to deal with clefs and custos inside a syllable. And this *should* only occur with syllables spanning a system break, which we fake with two syllables in neon.

**Comment by JRegimbal** [comment]
New script seems to be working or close to it but automated tests won't run with the current version of JSDOM as certain required classes (e.g., `XMLSerializer`) or functions (`Element.insertAdjacentElement`) are not supported in the version bundled with jest . This is bad since these are called in `NeonCore.test.ts` as well as `ConvertMei.test.ts`.

**Comment by kemalkongar** [comment]
@JRegimbal Was this issue fixed by the above mentioned merge?

**Comment by JRegimbal** [comment]
Yes I believe this would've fixed it.

**Comment by kemalkongar** [comment]
Given the fix, closing until it reappears.
