### ISSUE TITLE
Avoid custos within sb

### ISSUE THREAD

**Issue by rettinghaus** [DDMAL/Neon#604]
`sb` elements should not contain a `custos` element. They should be siblings.

**Comment by JRegimbal** [comment]
The guidelines say that an `sb` element may contain a `custos`. Is this an error or only for specific cases?

**Comment by rettinghaus** [comment]
There is (or was) an error in the guidelines, see https://github.com/music-encoding/music-encoding/issues/629 and the fix in https://github.com/music-encoding/music-encoding/pull/630
`<sb>` should be empty. It marks a *system beginning* while a `custos` is found at the ending of a system.

**Comment by JRegimbal** [comment]
Ah alright. The [current guidelines for `sb`](https://music-encoding.org/guidelines/v4/elements/sb.html) still list `custos` as being a valid child. We did think that was strange but not so much as to question it.
