### ISSUE TITLE
ungrouping syllables , invalid MEI

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#644]
For some syllables, ungrouping them into separate syllables makes the MEI file invalid (though visually the result is as desired.)
This occurred several times on folio 007r, e.g. at the end of line 7, the beginning of line 8, and the overlong syllable in line 9.
Validation logs for all of these are variations of the attached.
[validation (2).log](https://github.com/DDMAL/Neon/files/5197899/validation.2.log)
Valid state:
![image](https://user-images.githubusercontent.com/67451875/92653698-bacd1f80-f2bc-11ea-9b4c-4aa31312cb17.png)
Invalid state after ungrouping one syllable:
![image](https://user-images.githubusercontent.com/67451875/92653765-d46e6700-f2bc-11ea-87b0-4e2e65126f7a.png)

**Comment by annamorphism** [comment]
Another example, on the very first folio: 
![image](https://user-images.githubusercontent.com/67451875/94861278-3e35e880-0405-11eb-8d60-09c9559ae39b.png)
![image](https://user-images.githubusercontent.com/67451875/94861306-4beb6e00-0405-11eb-9a62-7824a49ff299.png)
[validation (11).log](https://github.com/DDMAL/Neon/files/5314620/validation.11.log)

**Comment by JRegimbal** [comment]
Sorry for the very, very long delay on this! It seems that the new zones for ungrouped syllables are being added to the surface element twice. I made a PR to verovio to take care of this and once it's merged I'll update Neon.
