### ISSUE TITLE
custos behaviour inconsistent

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#645]
Inserting a custos seems to behave differently in places (possibly, but not consistently, depending on the angle of staff lines.) In a staff that is straight or angled down, the custos note is generally within half a space of the click (n.b. this click area should probably be centered around a staff line rather than being exclusively on one side of it). But on an upwardly angled staff the custos sometimes (but not always!) lands about an entire staff line below the click.

**Comment by JoyfulGen** [comment]
This is also true when trying to move the custos; to get it to land on, say, the third staff line, you have to drag it to the fourth (I exaggerated the tilt of the staff to illustrate).

https://user-images.githubusercontent.com/83373378/152800664-645ee830-b7a7-42c7-b975-5df78cee54d2.mov

**Comment by jinh0** [comment]
Accidentals also seem to have the same problem.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. Please let us know if anything unexpected happens.
