### ISSUE TITLE
Feature request: a button to correct octave displacement

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#648]
It is always assumed that a C clef denotes C3 and F-clef F3, but this is not always true. This leads to problems e.g. folio 1r lines 5-6, where two consecutive E's are labelled E3 and E2 because of a clef change.  The user should be able to correct such octave displacements when they arise. 
![image](https://user-images.githubusercontent.com/67451875/105764839-82ee0e00-5f25-11eb-9ccd-fc4bd99aef3f.png)

**Comment by JoyfulGen** [comment]
This also applies for this issue https://github.com/DDMAL/Neon/issues/655

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for the clef displacement dropdown.

@jinh0, could you please add the displacement info to the display info box? Is this possible?

**Comment by JoyfulGen** [comment]
Everything looks great with the clef displacement! When I change the clef octave, the pitches of the neumes following change accordingly.
