### ISSUE TITLE
ex-ligatures retaining information

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#649]
Neume components that were previously ligatured behave as if they were ligatured even when the ligature is untoggled e.g.  the pitches of the puncta are read from higher to lower rather than left to right.  

![image](https://user-images.githubusercontent.com/67451875/105782089-cce4ed00-5f41-11eb-8341-84b8a54464c6.png)

**Comment by JoyfulGen** [comment]
Somewhere along the line, maybe when https://github.com/DDMAL/Neon/issues/641 or https://github.com/DDMAL/Neon/issues/724 were fixed, this issue was fixed as well. I'm closing it now.
