### ISSUE TITLE
syllable problems 

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#659]
Folio 123v of Salzinnes has some strange content. Only the first few neumes belong to a blank syllable <>; the next lines not only are not mapped to a <>, but several neumes are apparently part of two syllables (!). Nevertheless the MEI claims to be valid...

**Comment by annamorphism** [comment]
![image](https://user-images.githubusercontent.com/67451875/112885805-2df28380-909f-11eb-9442-41c05be1be7a.png) first syllable selected by hovering over text
![image](https://user-images.githubusercontent.com/67451875/112885846-377beb80-909f-11eb-99a1-c70007f699bd.png) first syllable selected by clicking
syllable 2?: 
![image](https://user-images.githubusercontent.com/67451875/112885996-5ed2b880-909f-11eb-8826-d5b64d676c7c.png)
syllable 3?: 
![image](https://user-images.githubusercontent.com/67451875/112886022-698d4d80-909f-11eb-80cf-dbc738358990.png)

**Comment by JoyfulGen** [comment]
@annamorphism I know this was a while ago, but this looks to me like what happens when the text file and folio image that were assigned in the OMR process don't match. When the text file is wrong, Neon does its best to assign syllables, but none of it matches, so we end up with these super long syllables (I've made the mistake myself a couple of times and have paid for it dearly). Could that be the issue here?

**Comment by annamorphism** [comment]
@JoyfulGen That seems to be part of it. This text goes across multiple pages, and it looks like although it successfully "picks up" the second page of text from where it left off the first, the third is a mystery until the next chant begins, halfway down the page.
So we need something to deal with a chant text that goes across >2 pages and correctly assign it to the right page.
But usually Neon does a better job creating blank syllables and doesn't double-assign things, so that's a bug that needs correcting too--so that in situations where the text is misaligned or missing the results aren't this strange.

**Comment by annamorphism** [comment]
On the page itself, we appear to have 8 syllables and one blank text marker, which is connected to the orange syllable (if you hover over the marker itself), the orange and blue (if you click on the orange), or orange, blue, and green (if you click on the blue.) The others aren't associated with any "text" at all.
![image](https://user-images.githubusercontent.com/67451875/152417291-3f92e25f-6c30-4e06-9114-8494cc3df5a1.png)
Looking at the MEI file, I think the intention was to create one long linked syllable to the single blank marker, but it doesn't work, because several syllables cross a staff break. E.g. the orange and blue are one syllable in the MEI but two on the page, as are green/yellow, blue/orange, and pink/light orange. The usual "follows" markers are there to connect these syllables (e.g. yellow to blue) but since several of them are broken it doesn't work properly.  Here's some colour-coded MEI: what we see as orange and blue is all under one syllable, while the green is a separate linked syllable.
![image](https://user-images.githubusercontent.com/67451875/152418487-1a42c2bd-c551-4ba1-80fd-324f2d311b5a.png)

I don't know why SOME syllables ended up correctly split into two across the staff break and then linked with a "follows" attribute, while others did not, but it should really be happening for all of them. Alternatively, separate, not-linked syllables for each line would be fine too; basically we want to be able to work with a page properly even when there is no text provided.

**Comment by JoyfulGen** [comment]
To our future selves: @annamorphism and @JoyfulGen please investigate further

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @annamorphism, could you please make the issue title more descriptive?

**Comment by annamorphism** [comment]
oof. @JoyfulGen did you ever investigate further? There seem to have been several problems going on here at once...

**Comment by JoyfulGen** [comment]
@annamorphism and @yinanazhou, this looks to me like a series of problems that have since been solved. In the folio Anna describes, the syllables are way too big, so they include clefs and <sb> elements, and that's creating chaos. I think this is directly related to https://github.com/DDMAL/Rodan/issues/634, which was solved a while ago. I'll actually close the issue, since it's pretty broad anyway.
