### ISSUE TITLE
Feature request: accidentals

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon#661]
The Neon interface doesn't allow to insert accidentals. The only primitives supported are punctum, virga, inclinatum, custos, C clef, and F clef. It would be nice if it allowed also for inserting flats and sharps since there are accidentals in neumatic notation.

**Comment by martha-thomae** [comment]
I am including an example of a flat in the Salzinnes manuscript, folio 9r (see pink circle):
![Screen Shot 2021-04-22 at 3 09 34 PM](https://user-images.githubusercontent.com/13948831/115772471-27dd8300-a37d-11eb-936b-e20651e93847.png)

**Comment by carrieeex** [comment]
Apparently, naturals are also in the Salzinnes manuscript. So far we've found them in folios 129r, 168v and 177v. Here's an example in folio 177v:
<img width="483" alt="177v flat and natural" src="https://user-images.githubusercontent.com/59303880/126487771-599c29c3-30c4-4bfe-af95-d05edc33c025.png">

**Comment by martha-thomae** [comment]
Accidentals should be implemented with the element `<accid>` included in the `<layer>` element. It should use the `@accid` attribute to indicate the type of accidental. Assuming we are only encoding _flats_ and _naturals_, we only need two values for this attribute `f` and `n`. Therefore, we have two options for `<accid>`:
- `<accid accid="f">` for a flat
- `<accid accid="n">` for a natural

Also, it might be useful to encode the relation between the accidental and the note it is affecting. This can be done with an attribute `@corresp`which points to the `xml:id` of the note affected by the accidental. This last point—relating the accidental to the note it affects—can be optional, since this is a matter of interpretation. 

The discussion of this decision can be found here in the music-encoding [issue # 816](https://github.com/music-encoding/music-encoding/issues/816)

**Comment by GabbyHalpin** [comment]
Update: The front end of this issue is complete. I am now working on the backend. So Far, I have run into an issue where the <accid> tag is not recognized by Verovio.

**Comment by GabbyHalpin** [comment]
Update: I have made progress!!! I have fixed the inputForm error that was causing the image to become undefined (Shoutout to @JRegimbal for the help). Now The accidentals are being added to the Mei file and there no errors being thrown. However, The added acids are not showing up on the frontend of Neon, and the specific accid info is not included in the Mei file ex: accid = 'f'. I will now be working on this.

**Comment by GabbyHalpin** [comment]
GOOD NEWS: I have gotten the accidentals to show up on screen. its is very close to being fully functional.
WEIRD NEWS: It would seem that when we add an accidental, then add another to another note, the first on disappears. If I were to add a third, the first would reappear, the second would disappears and the third would be placed no issue. there would be this weird alternation every time we add an accidental.

https://user-images.githubusercontent.com/68965715/129772016-6f2bc696-30d8-4d83-9215-c787e878f66a.mov

**Comment by martha-thomae** [comment]
Hi @GabbyHalpin! This looks amazing. Even with the accidentals disappearing for some unknown reason, they look nice when they do appear. Could you send me the MEI files generated by each addition of these 3 accidentals? I want to see how they are encoded and if that also explains why they are dissapearing.

**Comment by GabbyHalpin** [comment]
Hello! I have some great news! The disappearing issue has been fixed. It in the View_element.cpp file and one variable was called accid rather than element. The changes are now up on accid_fix and will be pushed as soon as possible once we have tested it to make sure there are no resulting issues.

**Comment by yinanazhou** [comment]
I tested locally. The disappearing issue has gone on my end. But @carrieeex and I found a new issue that when we added an accid in neon, saved that file and input it again to neon, neon does not show that accid.

**Comment by GabbyHalpin** [comment]
We have now completed the accidentals feature. If there are any new features or things you would like us to add, please let us know. Let me know if we are allowed to close this issue

**Comment by annamorphism** [comment]
Question on this feature: is it possible to have the accidental appear on the correct line, rather than just the top one?

also, minor point, but the menu for users should say "change accidental" (or "change accidental shape"), rather than "accid".

**Comment by yinanazhou** [comment]
Hi @annamorphism , I have already changed the menu. 

As for the accidental position, it is quite complicated. In MEI encoding, the position (pitch) of the accidental is defined by the `@corresp` attribute, which gives the `@xml:id` of the neume component that the accidental is attached to. But in the manuscript, we don't know which neume component the accidental is attached to. 

One possible solution is to add a button that can move accidentals downwards by changing `@uly` and `@lry` in `@zone` in facsimile. Please tell me what you think.

**Comment by annamorphism** [comment]
@yinanazhou does it help to know that in virtually all cases, the accidental should be on the pitch B/B-flat? In some cases this alone will be unambiguous, but just in case, the nearest neume on a B should clear things up.  So a possible "cheat" might be to default to the accidental being on B instead of on the top line (like now).  If it *has* to be given with an xml id, I guess you could look forward to the next nc with pitch=b (though that seems sort of annoyingly circular when we already know where B is!)
An up-down button might still be useful just in case there are weird exceptions (these should be really, really rare; I don't think anybody has seen any in the manuscripts we're working with right now), or in case it's the wrong octave or something.  It would also be a workable solution if the @corresp attribute is just too cumbersome to work deal with.

**Comment by JoyfulGen** [comment]
I made a new issue for the the requests remaining https://github.com/DDMAL/Neon/issues/852, so I'm closing this one.
