### ISSUE TITLE
Glyph Opacity slider lacks immediate visual change when applied 

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#662]
Glyph Opacity Slider will only be applied when a new page is loaded (aside from the first page)
Workaround: Apply desired Glyph Opacity Slider setting, scroll to a new page, desired setting should be applied. 

https://user-images.githubusercontent.com/62864127/117306616-cffb4d80-ae4d-11eb-8de1-4b4e14432ba7.mp4

**Comment by annamorphism** [comment]
This is also true in browser (1c34e14)

**Comment by kemalkongar** [comment]
Scrolling up to your active page with the changed opacity then scrolling back down will update all pages -- you need to visit the original page for the settings to be applied. Currently working on a fix.

**Comment by kemalkongar** [comment]
Issue has been fixed in `dev2021`, will test further and open a PR.

**Comment by kemalkongar** [comment]
Fixed in PR #684
