### ISSUE TITLE
Some neumes not grouping

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#671]
When we select a group of neumes and click on "group neumes," two things are supposed to happen: the "group neumes" button disappears and a notification appears in the top left corner indicating that the grouping was successful:
<img width="1072" alt="Screen Shot 2021-05-17 at 8 34 20 AM" src="https://user-images.githubusercontent.com/83373378/118490074-8b906d00-b6eb-11eb-8ef2-fe6edc766fc4.png">
However, on occasion (2-3 times a folio) neither of these things happen. The "group neumes" button becomes framed in blue, but stays there, and the neumes are never grouped:
<img width="1169" alt="Screen Shot 2021-05-17 at 8 33 13 AM" src="https://user-images.githubusercontent.com/83373378/118490103-9519d500-b6eb-11eb-8a93-47cc68960318.png">
The only solution we've found is to delete the neumes and reinsert them. The "new" neumes can be grouped without a problem.

**Comment by martha-thomae** [comment]
@JoyfulGen, thank you! I think we might need more information to debug this issue. Would you share the MEI file where this is happening? and also the actual code snippet for the neume(s) you are trying to group?

**Comment by annamorphism** [comment]
Is it always the same neumes on a given folio? wondering if something about those particular neumes is causing a hang.

**Comment by JoyfulGen** [comment]
Oops, I'm sorry, I didn't download the file before correcting it! I'll do so the next time it happens.

**Comment by JoyfulGen** [comment]
Hi again! So it happened again in folio 076r, in the word "clamabat:"
<img width="1440" alt="076r neumes won't group" src="https://user-images.githubusercontent.com/83373378/119671979-37326f00-be08-11eb-937d-f019727c90d8.png">
The MEI file: 
[076r neume won't group.zip](https://github.com/DDMAL/Neon/files/6547164/076r.neume.won.t.group.zip)
And the code snippet for the syllables "cla-ma:"
``` <syllable xml:id="m-7999ff0f-b6e2-4eb2-a244-b1f4d228f37c">
                                    <syl xml:id="m-e2f8bd2e-0092-4bbb-9d9c-47ed00e5602d" facs="#m-fb0f9c13-37b9-49cb-885e-e797d6e2af1b">cla</syl>
                                    <neume xml:id="m-d5aa98e2-86ae-402d-92fd-ff0256ad98c1">
                                        <nc xml:id="m-8ded0bca-e7b1-471e-ba32-bbe2621f447f" facs="#m-3193f272-0802-499d-b40b-135f0ed8e0de" oct="2" pname="a"/>
                                        <nc xml:id="m-f475eb87-ce81-4e62-875e-552c84f1fcf3" facs="#m-68786a88-038c-455e-a71c-5790b37d1af4" oct="3" pname="c"/>
                                    </neume>
                                </syllable>
                                <syllable xml:id="m-a9dc4829-a3b6-4565-8446-116cd58244f9" precedes="#m-873b6e44-49a7-41f5-9c50-e020d905a44d">
                                    <neume xml:id="m-9d8c7061-4ad7-45c5-8955-bf3a7e03d349">
                                        <nc xml:id="m-c18638b8-faea-4a97-aeb0-c87a3c7a04c3" facs="#m-8f05265b-c755-4f8b-af67-46359ca1333e" oct="3" pname="c"/>
                                        <nc xml:id="m-8cf6127e-ba77-4bcb-9472-13e1b3dd6fbb" facs="#m-214f4273-cda2-43f0-b00b-4123a759e112" oct="2" pname="b"/>
                                    </neume>
                                    <syl xml:id="m-e4dca867-1c12-4276-8fc5-7647dd728933" facs="#m-d8ccf2a6-805f-4d9d-9baa-ef416c5b79a9">ma</syl>
                                </syllable>
                                <syllable xml:id="m-873b6e44-49a7-41f5-9c50-e020d905a44d" follows="#m-a9dc4829-a3b6-4565-8446-116cd58244f9">
                                    <neume xml:id="m-e13514c8-61b3-4a51-94be-bb5bccce1f12">
                                        <nc xml:id="m-237ac504-3e9d-414c-ac16-3cf122fe1ffe" facs="#m-92880721-0400-4a7a-9312-60f18f74db1a" oct="3" pname="c"/>
                                        <nc xml:id="m-0cbfd2a4-efed-41c6-a2ed-a07413963654" facs="#m-c76d8057-83dd-4a6b-8d98-44584f7aead8" oct="2" pname="b" tilt="se"/>
                                    </neume>
                                    <neume xml:id="m-b928a529-3dad-4cc0-add3-7364aa0db045">
                                        <nc xml:id="m-4651a823-04b8-4a1d-a045-1360414e6e3b" facs="#m-10e16f0e-21de-44fe-a562-d259c42cd81c" oct="2" pname="b"/>
                                        <nc xml:id="m-49c1fdca-886a-47f1-8962-9d54afe05591" facs="#m-25836f27-8240-4bd3-a1de-3f49bdc9e610" oct="3" pname="c"/>
                                    </neume>
                                </syllable>
                                <syllable xml:id="syllable-0000002065366631">
                                    <neume xml:id="neume-0000000517449062">
                                        <nc xml:id="nc-0000000497005119" facs="#zone-0000000783650694" oct="2" pname="a" tilt="se"/>
                                    </neume>
                                    <syl xml:id="syl-0000001848106313" facs="#zone-0000000577167553"/>
                                </syllable> ```

**Comment by annamorphism** [comment]
I notice in the MEI that 1) the neumes are out of order and 2) the "syl" marker is after the neume marker instead of before it. Wondering if those two conditions combine to cause a grouping issue.

**Comment by annamorphism** [comment]
Don't yet know enough about this issue to test it in browser (1c34e14) but I don't think it's been addressed yet.

**Comment by kemalkongar** [comment]
<img width="1792" alt="Screen Shot 2021-06-16 at 2 36 07 PM" src="https://user-images.githubusercontent.com/47402993/122274164-3f824500-ceb0-11eb-8e12-bf9886f6d529.png">

In the given MEI file:

Verovio error in the console when multiple neumes are selected and the "Group Neumes" button is pressed.

**Comment by kemalkongar** [comment]
Traceback to `verovio-toolkit.js`    `return verovio.vrvToolkit.edit( this.ptr, JSON.stringify( editorAction ) );`

**Comment by kemalkongar** [comment]
Current idea:

- Neon gives an error when certain neueme groupings are selected and operations are called on it. 
- This causes verovio to give a `toolkit_edit` error in the cwrap - ccall.
- This can be traced back to `vrv::Toolkit::Edit`.
- Given this is a general function, we assume that the error is caused by the parameters passed into it -- more specifically the `Group` of neuemes. 
- Thus, the solution to this issue should be somewhere in the `EditorToolkitNeume::Group` method in `editortoolkit_neueme.cpp` around line 1522.

**Comment by GabbyHalpin** [comment]
There might be something related to the enumerated ID. We are noticing different types of ID used to identify neume groups. Also, we will be looking into how the elementID are created when highlighting the groups

**Comment by raviraina** [comment]
To elaborate on Gabby's comment,`editortoolkit_neume.cpp` may not be handling incorrect elementIds/uuids. Comparing successful vs. unsuccessful grouping objects in the log shows that the failed grouping has a non-standard id in the form of `neume-[some_numbers...]`. My assumption as of right now is that this form of ID is potentially incorrect, and when passed through the functions in Verovio, it is unable to handle it or recognize it as a valid ID.

**Comment by raviraina** [comment]
![Screen Shot 2021-06-18 at 4 19 44 PM](https://user-images.githubusercontent.com/14239364/122613286-9a53a200-d052-11eb-9d3f-8ee615ded25a.png)

For reference, top object groups/ungroups correctly, bottom one with the following TypeError does not.

**Comment by GabbyHalpin** [comment]
small update: It turns out that these tags are probably not the source of our issue.

**Comment by JoyfulGen** [comment]
I don't know exactly how, but it looks like this issue was fixed along the way. I haven't encountered it in ages, so I uploaded the file above and, even though the neumes are still in the wrong order at first, the order corrects itself when I group them.
