### ISSUE TITLE
Bounding boxes spawn adjacent to newly created symbol rather than below it

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#674]
When creating a new symbol (ex: punctum), the bounding box attached to it will appear to the symbol's bottom right rather than directly below it. 

![Screenshot_4](https://user-images.githubusercontent.com/62864127/118831759-07c2b600-b88e-11eb-908f-68c00933c78d.jpg)

**Comment by martha-thomae** [comment]
Very nice feature request and a good example of a first issue for developers to fix :)

**Comment by chetbae** [comment]
Bug fixed, pending approval from @yinanazhou !

https://user-images.githubusercontent.com/48145854/176601167-4df0a87d-bbac-4292-838c-1c5544d29c0a.mov

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes to `gh-pages`.
