### ISSUE TITLE
Way to input flats manually

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#678]
This issue https://github.com/DDMAL/MEI_encoding/issues/2 could be fixed by creating a way to input an accidental flat on Neon. Since there are very few, the manual input option would be very satisfactory.

**Comment by martha-thomae** [comment]
Short note: this is the same issue as https://github.com/DDMAL/Neon/issues/661. Very good observation that the manual option input in Neon would be satisfactory solution for the MEI Encoding issue.

**Comment by JoyfulGen** [comment]
As this is a duplicate of https://github.com/DDMAL/Neon/issues/661 and that flats can now be input manually, I'm going to close this issue.
