### ISSUE TITLE
Syllables without neume components

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#679]
It is possible when editing to delete the neume components of a syllable without deleting the entire syllable. The bounding box is then impossible to remove, because the neumes to which it is attached are invisible...
(In the image, the blank bounding box originally contained "e" but was moved to accommodate the bbox from the inserted neume in yellow.)

![image](https://user-images.githubusercontent.com/67451875/120580522-55473300-c3f7-11eb-880a-4d11b344dda9.png)

![image](https://user-images.githubusercontent.com/67451875/120580473-43659000-c3f7-11eb-87c9-bbd5bba2751c.png)

**Comment by JoyfulGen** [comment]
I think this has happened to me, but when it did I could select the bounding box and delete it by pressing the "delete" key on my keyboard. Could this work for you?

**Comment by annamorphism** [comment]
I thought that gave me a hang at the time, but it seems to work fine now...and I also haven't been able to recreate whatever steps led to the issue. Closing this issue.
