### ISSUE TITLE
Reassigning multiple syllables to nearest staff often impossible

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#681]
More often than not, if I select more than one syllable and click on "reasociate to nearest staff" the edges of the button stay blue and nothing happens, no matter how long I wait. I can only reassociate one syllable at a time. This isn't a huge issue, but it's slightly irksome (especially when I get issue https://github.com/DDMAL/MEI_encoding/issues/25 and I need to reassign an entire staff of syllables one at a time).

**Comment by JoyfulGen** [comment]
Upon further investigation it seems this same issue was raised and closed last year: https://github.com/DDMAL/Neon/issues/636

**Comment by kemalkongar** [comment]
Issue is present on the most recent local build. Working on a fix now.

**Comment by kemalkongar** [comment]
```
export function changeStaffHandler(): void {
  const toChange: EditorAction[] = [];
  const selected = Array.from(document.getElementsByClassName('selected'));
  selected.forEach(elem => {
    toChange.push(
      {
        'action': 'changeStaff',
        'param': {
          'elementId': elem.id
        }
      }
    );
  });
  const chainAction: EditorAction = {
    'action': 'chain',
    'param': toChange
  };
  console.log('Staff Change');
  endOptionsSelection();
  neonView.edit(chainAction, neonView.view.getCurrentPageURI()).then(() => { neonView.updateForCurrentPage(); });
}
```
The function that handles staff reassociation fails to reach the log statement if multiple syllables are selected. No issues with a single syllable.

**Comment by kemalkongar** [comment]
The function is simply not called with multiple syllables (sometimes ?) and a `console.log` right below the function declaration fails to print except with single syllable highlights.

**Comment by kemalkongar** [comment]
Line 249 `triggerSylActions` is not being called at all when multiple syllables are selected. So it doesn't get to reach the eventListener.

**Comment by kemalkongar** [comment]
Closed with #685

**Comment by JoyfulGen** [comment]
Testing only the Neon job on rodan staging, this issue occurred again in folio 147r.

**Comment by JoyfulGen** [comment]
I take back what I said! The devs did something (don't know what, but I'm grateful) and it works! Here's the same staff from yesterday, with its syllables all reassigning themselves in a most satisfactory fashion: 

https://user-images.githubusercontent.com/83373378/124016181-5c8c3d00-d9b3-11eb-9649-d7c4864c1769.mov

**Comment by kemalkongar** [comment]
Most likely b635d0f659f291425cba977b4c1cb4611f077a5e, it shows up now since we updated the Neon submodule inside neon_wrapper in the Docker scripts. Same for a lot of the fixed verovio issues.
