### ISSUE TITLE
Zooming in and/or dragging a folio too fast causes major slow down

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#683]
Any rapid combination of zooming or dragging commands makes neon slow way down, apparently regardless of how many people are using Rodan at that time. Sometimes the slow down lasts a few seconds, sometimes several minutes. If we make the same commands a bit slower, it's usually ok.

**Comment by raviraina** [comment]
@JoyfulGen Is this only a problem within Rodan or do you get the same issues running Neon as a standalone?

**Comment by JoyfulGen** [comment]
I'm getting the problem in Rodan, I don't know for the standalone!

**Comment by annamorphism** [comment]
wondering if this is a variation on https://github.com/DDMAL/Neon/issues/652 where the issue was the number of pages being scrolled through rather than the speed of the command.

**Comment by JoyfulGen** [comment]
Zoom slider is fixed! I can zoom as enthusiastically as I want, no slow down. Closing the issue now.

**Comment by JoyfulGen** [comment]
Oops, sorry, I'm going to reopen the issue for a small detail. @jinh0, it used to be that clicking on the "Zoom" button made the zoom jump to 100 automatically, but now that doesn't seem to work anymore. The slider goes to 100, but the image doesn't change. Would it be possible to re-implement that function?

**Comment by jinh0** [comment]
Huh, that's weird, I'll look into that.

**Comment by JoyfulGen** [comment]
Issue fixed! Closing it now.
