### ISSUE TITLE
Browser neon will allow any file format to be uploaded regardless of options

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#689]
When attempting to upload a file (either MEI or Picture file), Neon in browser will be able to accept and process any files.
Incorrect files should be rejected, to avoid user-side error.

**Comment by GabbyHalpin** [comment]
Hey @thesoundbyle! I I have a few follow up questions for this issue. For one, does this occur in many browsers, or only in one, and if so, which one? I'm just checking since I don't seem to get the same issue when using browser Neon in safari nor in google.

**Comment by thesoundbyle** [comment]
> Hey @thesoundbyle! I I have a few follow up questions for this issue. For one, does this occur in many browsers, or only in one, and if so, which one? I'm just checking since I don't seem to get the same issue when using browser Neon in safari nor in google.

Hey @GabbyHalpin , I've confirmed it happens on chrome and edge (on windows). That my fault for not clearly writing the steps to properly reproduce this issue. But while selecting a file, I have the option to select any file by clicking the "All Files" option in the bottom left of windows explorer. Attached is a screenshot to further illustrate what I'm explaining. 

![Screenshot_1](https://user-images.githubusercontent.com/62864127/124770231-2c3f2400-df08-11eb-8ea5-d214b0e762a4.jpg)

**Comment by yinanazhou** [comment]
This issue has already been fixed in the latest version of upload page.
