### ISSUE TITLE
Feature Request: the option to remove folios from browser Neon

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#690]

**Comment by martha-thomae** [comment]
Hi @thesoundbyle , could you clarify what this issue entails? it is not clear from the title. Could you add a description for clarification? Thank you.

**Comment by thesoundbyle** [comment]
currently, on the selection page of browser neon, the user has no way of removing a folio/manuscript from the interface

**Comment by carrieeex** [comment]
Currently, the user can load a new document in the browser Neon, but they cannot delete a specific document they uploaded. The only way to delete the documents seems to clear the cookies and site data, which clears everything (all the documents they have uploaded).

**Comment by annamorphism** [comment]
Note that this means if you accidentally mismatch an image and MEI while uploading many files, it becomes hard to correctly reassign them without clearing everything, so it's an impediment to doing lots of pages at once.  (The upload times out if you try to upload the same image with a different MEI, or at least it does for me.)

**Comment by JoyfulGen** [comment]
The new feature works! I can remove individual files from browser Neon very easily. Thank you!

**Comment by JoyfulGen** [comment]
Now that I've tried out this new feature more extensively, I'd like to make another little request: could there be a sort of "Are you sure you want to delete this?" message when the user clicks on delete? I may or may not have just accidentally deleted the file I was working on... twice.

**Comment by chetbae** [comment]
@JoyfulGen Changes should be live! Working on a new page soon.

**Comment by JoyfulGen** [comment]
Changes work! I see the "are you sure" message now, so I can go back to recklessly clicking a top speed without worrying too much. Thanks @chetbae!

**Comment by chetbae** [comment]
@JoyfulGen @annamorphism 
Big mistake on my part! Changes have been reviewed and are live.

**Comment by JoyfulGen** [comment]
The fix works! "Cancel" cancels and "Delete" deletes. Closing issue now.
