### ISSUE TITLE
Cannot merge more than 2 syllables in browser Neon

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Neon#692]
In the [browser version of Neon](https://ddmal.music.mcgill.ca/Neon/), the "merge syllables" option is only effective when the user selects 2 syllables. If more than 2 syllables are selected, the expected "merge syllables" option is not given. Instead, the "ungroup" option is given; and if the user clicks "ungroup" in this case, the MEI Status becomes invalid and extra bounding boxes appear. The illustrations are shown below. This only happens in the browser, not in Neon in Rodan2.

1. a. the normal case (select two syllables in browser Neon):
<img width="1103" alt="108v browser Neon 2 syllables normal" src="https://user-images.githubusercontent.com/59303880/122808566-0fb1b380-d29b-11eb-9ad0-381b4d8e1d7c.png">
b. and the same shows in Neon in Rodan2:
<img width="1128" alt="108v Rodan2version Neon 2 syllables normal" src="https://user-images.githubusercontent.com/59303880/122808643-22c48380-d29b-11eb-93ca-9222d28535b4.png">

2. a. if selecting more than 2 syllables (here I selected 4 in Neon in Rodan2), we would expect the same options:
<img width="947" alt="108v Rodan2version Neon 4 syllables normal" src="https://user-images.githubusercontent.com/59303880/122808785-4e476e00-d29b-11eb-887e-622bb088d37d.png">
b. However, in the browser, it shows like:
<img width="1090" alt="108v browser Neon 4 syllables no merge" src="https://user-images.githubusercontent.com/59303880/122808898-6dde9680-d29b-11eb-8a21-c5f5c906e97e.png">
3. and if I click "ungroup" option in 2b, MEI becomes invalid and extra bounding boxes will appear:
<img width="1076" alt="108v browser Neon 4 syllables ungroup" src="https://user-images.githubusercontent.com/59303880/122808942-7b941c00-d29b-11eb-89a0-9b2686e0060e.png">

The images above are [Salzinnes folio 108v](https://mcgill-my.sharepoint.com/:i:/r/personal/martha_thomaeelias_mcgill_ca/Documents/DDMAL_Manuscripts/Salzinnes_Antiphonal%20-%20New%20Images/OnlyMusicFolios_and_Renamed/Halifax_-_Saint_Mary_s_University_-_Patrick_Power_Library_-_ms._M2149.L4_I_108v.png?csf=1&web=1&e=Yvplbd). 
The valid MEI file for step 2a is:
[108v valid before extra bbox.zip](https://github.com/DDMAL/Neon/files/6688719/108v.valid.before.extra.bbox.zip)
and the invalid MEI file for step 3 is:
[108v invalid due to extra bbox.zip](https://github.com/DDMAL/Neon/files/6688722/108v.invalid.due.to.extra.bbox.zip)
with the log file: 
[validation - 108v invalid due to extra bbox.log](https://github.com/DDMAL/Neon/files/6688724/validation.-.108v.invalid.due.to.extra.bbox.log)

> file_0.xml:673: element neume: validity error : ID m-9b7707d4-c308-4e43-9bda-b723de87e82b already defined
                          <neume xml:id="m-9b7707d4-c308-4e43-9bda-b723de87e82b"
                                                                               ^
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
-be9685b6189f" facs="#m-38e9e333-ed5c-4f61-b920-6a12df546519" oct="3" pname="d" 
                                                                               ^
file_0.xml:685: element neume: validity error : ID m-36d43be9-f2e2-49cb-bee8-970b656fbed0 already defined
                          <neume xml:id="m-36d43be9-f2e2-49cb-bee8-970b656fbed0"
                                                                               ^
file_0.xml:686: element nc: validity error : ID m-c3ff4f61-3c73-47de-a62d-4c0361a1b87d already defined
-4c0361a1b87d" facs="#m-f230c98d-489a-4e22-9d47-72fad8adb970" oct="3" pname="d" 
                                                                               ^
file_0.xml:697: element neume: validity error : ID m-42e4ed40-4a73-439e-9311-95e7504df2e1 already defined
                          <neume xml:id="m-42e4ed40-4a73-439e-9311-95e7504df2e1"
                                                                               ^
file_0.xml:698: element nc: validity error : ID m-114759d4-c170-41a1-8500-df9e63924e09 already defined
-df9e63924e09" facs="#m-8d7bfe6d-2b2d-4c07-88e2-2c30eb804bab" oct="3" pname="d" 
                                                                               ^
file_0.xml:673: element neume: validity error : ID m-9b7707d4-c308-4e43-9bda-b723de87e82b already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
file_0.xml:674: element nc: validity error : ID m-7fa5957e-cfdf-431d-a90d-be9685b6189f already defined
...
file_0.xml:674: element nc: Relax-NG validity error : Expecting an element app, got nothing
file_0.xml:674: element nc: Relax-NG validity error : Invalid attribute id for element nc
file_0.xml:674: element nc: Relax-NG validity error : Element neume has extra content: nc
file_0.xml:673: element neume: Relax-NG validity error : Element syllable has extra content: neume
file_0.xml:607: element clef: Relax-NG validity error : Element layer has extra content: clef
>

According to the log file, it seems that by ungrouping the syllables, an extra syllable element with no text will be created. For example, for the syllable "fi" in the image, an extra syllable with the same neume and nc xml id will be generated (line 668-673 and 674-679 in the invalid MEI file):
```
                                <syllable xml:id="m-a7f5c801-f36c-40d7-8df1-22a44f547e84">
                                    <syl xml:id="m-7d8fed99-daa2-49ef-a877-38631c49d66f" facs="#m-6fa9e0c7-ab70-4d61-8489-50dcae4ab991">fi</syl>
                                    <neume xml:id="m-9b7707d4-c308-4e43-9bda-b723de87e82b">
                                        <nc xml:id="m-7fa5957e-cfdf-431d-a90d-be9685b6189f" facs="#m-38e9e333-ed5c-4f61-b920-6a12df546519" oct="3" pname="d"/>
                                    </neume>
                                </syllable>
                                <syllable xml:id="syllable-0000002039620334">
                                    <neume xml:id="m-9b7707d4-c308-4e43-9bda-b723de87e82b">
                                        <nc xml:id="m-7fa5957e-cfdf-431d-a90d-be9685b6189f" facs="#m-38e9e333-ed5c-4f61-b920-6a12df546519" oct="3" pname="d"/>
                                    </neume>
                                    <syl xml:id="syl-0000000310284809" facs="#zone-0000000613357214"/>
                                </syllable>
```

**Comment by kemalkongar** [comment]
Issue is replicated on browser Neon. It does not appear to be an issue on local Neon. We will investigate the cause.

**Comment by JoyfulGen** [comment]
Update: the same issue happens identically in Neon staging: 
<img width="1389" alt="131r can't merge (staging)" src="https://user-images.githubusercontent.com/83373378/124126064-467c8c00-da48-11eb-9877-bb683dea5c88.png">

The consequence of ungrouping the syllables is also the same (new bounding boxes, invalid file):
<img width="913" alt="131r too many BBs (staging)" src="https://user-images.githubusercontent.com/83373378/124126454-affc9a80-da48-11eb-8f2c-dedd59fa41d9.png">
[131r too many bounding boxes (staging).zip](https://github.com/DDMAL/Neon/files/6748142/131r.too.many.bounding.boxes.staging.zip)

I also noticed that if I delete the extra bounding boxes, the syllables get deleted as well, even though the colours suggest they're not linked. This is weird.

https://user-images.githubusercontent.com/83373378/124126652-e2a69300-da48-11eb-9dc9-9644a1b05f1a.mov
