### ISSUE TITLE
Button to change neume grouping only creates pedes

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#694]
When a neume is selected, the option for a drop-down menu appears and suggests various neume groupings. However, selecting any of these groupings except for pes doesn't seem to do anything at all. The pes selection, regardless of the neume and pitches, makes a stepwise pes starting from the first neume component and deletes the rest. Some examples from folio 161r:

https://user-images.githubusercontent.com/83373378/123648507-ff4b8c80-d7f6-11eb-8dbf-1201a27dd8a7.mov

https://user-images.githubusercontent.com/83373378/123648587-0e323f00-d7f7-11eb-8654-1dff1d2844b5.mov

https://user-images.githubusercontent.com/83373378/123648684-2609c300-d7f7-11eb-80fd-1e3fde455d6f.mov

This drop-down menu would be very useful if it allowed the user to split a neume into two specific groupings. At the moment, splitting a neume in two requires us to ungroup the entire neume and then group the neumes and neume components of the neumes we want. Selecting the grouping of the first neume would divide the neume correctly in one click and significantly speed up the process.

**Comment by raviraina** [comment]
@JoyfulGen Could you try and replicate the issue either through standalone Neon or on rodan-staging please!

**Comment by JoyfulGen** [comment]
Update: @raviraina I just tried on rodan-staging and the issue is exactly the same.

**Comment by JoyfulGen** [comment]
This issue has been fixed, closing it now.
