### ISSUE TITLE
Cannot upload MEI files when using safari/chrome

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon#695]
When uploading a new page in browser neon using safari or chrome, the default file type for `an MEI neume file` is `XML` file, which makes `MEI` files are grey and cannot be selected and uploaded in these two browsers.
![Screen Shot 2021-06-30 at 9 47 16 AM](https://user-images.githubusercontent.com/74484576/123978086-90ed0280-d98d-11eb-8860-fa3a75440921.png)

**Comment by GabbyHalpin** [comment]
So this has been fixed remotely we will probably upload the changes tomorrow!
