### ISSUE TITLE
merging syllables not always possible

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#696]
For some pairs of syllables one gets the option to "merge syllables" as below, on 11r:
![image](https://user-images.githubusercontent.com/67451875/124213231-343d3500-dabe-11eb-8be0-43cb9d801b3c.png)
For others, one does not get this option, but has to "group neumes" (which produces the same result).
![image](https://user-images.githubusercontent.com/67451875/124213170-1bcd1a80-dabe-11eb-8d2a-102010830562.png)
It is not obvious what condition causes this different behaviour.
snippet for first case:
![image](https://user-images.githubusercontent.com/67451875/124213408-7ebeb180-dabe-11eb-8b1a-8b55fff45d6f.png)
and the other:
![image](https://user-images.githubusercontent.com/67451875/124213438-8e3dfa80-dabe-11eb-9232-40536a9732a3.png)

[11r-syllable-merge.zip](https://github.com/DDMAL/Neon/files/6751776/11r-syllable-merge.zip)

**Comment by JoyfulGen** [comment]
This looks like the same issue as https://github.com/DDMAL/Neon/issues/676! One of the consequences of the syllable having no options is that you can't delete it or merge it.

**Comment by yinanazhou** [comment]
The second case would be fixed in the latest merge. In the first case, I was able to merge the two syllables, but the `bbox` of the first syllable is somehow invisible. I have checked the `bbox` coordinates, it's not flipped. @annamorphism and @JoyfulGen, does this issue happen often recently?

**Comment by JoyfulGen** [comment]
I'm having trouble uploading this to browser Neon for some reason, so I can't be sure, but I think the bbox you're talking about @yinanazhou is invisible because it doesn't have text associated to it. I think if you enter text to replace the little diamond, the bbox will appear.

**Comment by JoyfulGen** [comment]
I believe this issue was fixed here https://github.com/DDMAL/Neon/issues/676, so I'm now closing it.
