### ISSUE TITLE
Correct virga encoding

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon#703]
The encoding of the virga should use a `@tilt=s` (south) attribute since the tail of the virga goes down. Currently, the file exported by Neon always encodes virgas with `@tilt=n` (north).

Verovio only renders the latter as a virga (`@tilt=n`), so this should be corrected in Verovio too.

**Comment by carrieeex** [comment]
The "reversed virga" neume component is working properly in Neon in staging!

An example in Salzinnes 001r:
![image](https://user-images.githubusercontent.com/59303880/130800418-0b0fb25f-0d3e-4241-b881-051a40bf2e8b.png)

and in its MEI it looks like:
`                                        <nc xml:id="m-64fafff4-cece-48f6-8038-5150f85224f7" facs="#m-7e023dcf-c335-4834-a8f0-254d18f0879b" oct="3" pname="g" tilt="n"/>` 
which is correct.

and an example of "virga":
![image](https://user-images.githubusercontent.com/59303880/130800924-785f2e2b-2e41-4ea0-a4ec-466d293100ee.png)
` <nc xml:id="nc-0000001388505490" facs="#zone-0000001721041191" oct="3" pname="g" tilt="s"/>`

**Comment by martha-thomae** [comment]
Perfect. Thanks for confirming this, @carrieeex ! Will close this issue then :)
