### ISSUE TITLE
Support for liquescent

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon#704]
Add a primitive for liquescent. You can find the encoding of liquescent [here](https://music-encoding.org/guidelines/v4/content/neumes.html), there are a couple of examples.

The testers didn't find liquescent neumes on Salzinnes. However, there are many of them in MS73 and Einsiedeln.

Just a few examples found by Jiali in MS73:

<img width="959" alt="006 010 neume" src="https://user-images.githubusercontent.com/13948831/129912591-b42e29df-ee20-4698-958d-d0adc3148d54.PNG">

**Comment by JoyfulGen** [comment]
The liquescents work perfectly in rodan_staging as well! Closing the issue now.
