### ISSUE TITLE
Update MEI schema version (invalid 'rotate' attribute)

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon#710]
There is a `@rotate` attribute that is included in the `<zone>` element when a staff is rotated in Neon. This attribute is supposed to be invalid in the version of MEI we are using [version 4.0.0](https://music-encoding.org/guidelines/v4/content/#). The `@rotate` attribute will be included in the schema in the next MEI release (version [5.0.0-dev](https://music-encoding.org/guidelines/dev/content/index.html)).

Neon shows as valid MEI files that do include the `@rotate` attribute, despite using a version of MEI where this attribute would be invalid. Probably there is a modified version of the 4.0.0 schema running within Neon. However, the file exported doesn't provide this Neon internal customization, but references the regular 4.0.0 schema, where this attribute would be invalid. When opening the file in any other editor with validation (like Oxygen or [Verovio Editor](https://editor.verovio.org/)), the same file shows as invalid. (The file references the schema in the XML processing instructions at the beginning of the file and in its `<mei>` root element as can be seen in [this comment](https://github.com/DDMAL/Neon/issues/709#issuecomment-907544367).)

I think it would be better to just update the version of the schema used in Neon to 5.0.0-dev rather than using an internal customization. Updating the schema version will also be helpful for issue #709.

**Comment by martha-thomae** [comment]
By the way, it might be worth consulting @JRegimbal about this before making any decisions about updating the version of the schema being used or removing any customization within Neon.

Maybe we don't need to update the internal schema on Neon, but it might be good for the files coming out to reference the right schema where everything encoded is valid. And this can be easily achieved by just changing the XML processing instructions and MEI root element lines to reference the 5.0.0-dev version. Again, consulting this with Juliette before making any decisions would be the best way to go.

**Comment by JRegimbal** [comment]
AFAIK none of the breaking changes between 4 and 5.0.0-dev would break Neon, but it would be worth running the output files against that dev schema first.

**Comment by yinanazhou** [comment]
I have already updated MEI to `5.0.0-dev` in the `update-mei` branch. It is worth noting that the MEI files we have produced before are all in `4.0.0`, so if we input those files directly into neon, it would be `invalid`. But once it is edited (like one move), the file would be rewritten, and it would be `valid`.

**Comment by yinanazhou** [comment]
Hi @martha-thomae, could you please confirm that this issue can be closed?
