### ISSUE TITLE
The Layer Element is not highlighted when "Highlight by Selection Mode" is chosen in browser Neon

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Neon#718]
The Layer Element is not highlighted when "Highlight by Selection Mode" is chosen in browser Neon (they can be selected or edited, i.e. functioning well). The neumes are highlighted.

When "Highlight - Selection" is chosen, and choose Layer Element, accidentals are highlighted as expected as follows:
![image](https://user-images.githubusercontent.com/59303880/134360244-03cc1f66-a2a7-48d9-b7a9-1d8880644084.png)

While once the user clicks anywhere in the page, the neumes are highlighted:
![image](https://user-images.githubusercontent.com/59303880/134360909-1a24ed92-8ba7-4ba9-bb55-ef2c7e4ed388.png)

**Comment by yinanazhou** [comment]
I will add the option `Highlight - Layer Element` in the highlight menu and complete its function.
