### ISSUE TITLE
Moving and grouping neume components changes pitch order

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#722]
**EDIT: Please refer to my December 16th comment for a summary of the situation and a temporary fix!**

This is issue is possibly related to https://github.com/DDMAL/MEI_encoding/issues/31.

When training the interactive classifier for the Einsiedeln manuscript, I taught it to recognize neume groupings, such as a pes or a clivis, as a whole. This means that when a folio ends up in Neon after a full omr workflow, the pitches of these neumes are all correctly ordered. However, moving them sometimes changes the neume type, even though the neume components haven't moved in relation to each other. This is hard to explain, so here's video evidence:
In the Neume Info box in the bottom right corner, you can see that the neume is initially identified as a pes, which is correct, but when I move it it becomes a clivis and the pitch order changes.
https://user-images.githubusercontent.com/83373378/136577173-b6bfa892-6c26-4974-9464-6cc6dbc69e1e.mov

This also happens the other way around, with a clivis becoming a pes. It also seems to happen between the scandicus (three-note ascending neume) and the torculus (three-note up then down neume), but I don't have evidence of that yet.

Other features of note
- The issue only seems to happen when I use the neume component selection. If I move the neume using the neume selection, the neume type doesn't change.
Demonstration: https://user-images.githubusercontent.com/83373378/136577656-b9155a96-a7b6-4482-94ec-f86a93048fda.mov
- The issue also doesn't happen systematically. Some neumes don't change when I move them. Also, even more interesting, sometimes the result for the *same* neume is different. 
Here's a demo where I move one neume twice, and the result is different--the first time, the clivis remains a clivis, and the second time it becomes a pes, even though my behaviour is identical:
https://user-images.githubusercontent.com/83373378/136577951-94381a74-b4fc-4bef-921c-ddf09ac7431e.mov
https://user-images.githubusercontent.com/83373378/136577954-031364ad-2391-4764-85ff-cf1b7f784b0e.mov

Finally, the ordering issue now extends to inclinatums, for some reason. Neon will read an inclinatum that's clearly to the right of another one as coming before it. In the demo video, you can already see from the colours (green-blue-yellow when it should be green-yellow-blue) that the order of the pitches is wrong. Grouping the neume makes it clearer, because then you can see in the Neume Info box that Neon thinks the pitches are D3-F3-A2-C3, when they should be D3-F3-*C3*-*A2*. 
https://user-images.githubusercontent.com/83373378/136578783-3ab96c69-ba18-430c-afcb-63e2d55ebf16.mov
Moving the offending inclinatum fixes the issue. But this is really weird, because as far as I know, there's no instance in these manuscripts where a neume is read right to left.

**Comment by yinanazhou** [comment]
The issue also appears in browser neon.

**Comment by JoyfulGen** [comment]
A summary:

**The issue**: The individual neume components of a neume are sometimes ordered wrong in Neon. This can happen when moving a neume using the "neume component" selection, or when grouping neume components together. The pitch order of a same neume can change every time it's moved. However, it doesn't happen every time and the unifying factor is yet unknown.

**Where**: The issue happens in browser Neon, rodan2 and rodan_staging. So far it only happens with Einsiedeln folios, maybe because of the small size and high density of the neume components.

**Identifying the issue**: Most of the time, when the order of the neume components within a neume is wrong, the ordering of that neume relative to the ones around it will also be wrong, so the colour order will be too. The surest way to identify the problem though is just to look at the pitch order in the "Display info" section (see the many examples above).

**Fixing the issue**: Most of the time, moving the offending neume away and back again fixes everything. It also works to move one neume component slightly.

**Comment by yinanazhou** [comment]
I somehow have trouble reproducing this issue. @JoyfulGen, could you please upload an example file?

**Comment by JoyfulGen** [comment]
[005r_neume_grouping_examples.mei.zip](https://github.com/DDMAL/Neon/files/7802924/005r_neume_grouping_examples.mei.zip)
 
This is folio 005r, from Einsiedeln (it looks ugly, because I only worked on the two top staves, sorry). There are a few neumes that I managed to get reproducible results with:

- The first pes on the first staff (it's light orange) --> Using the "Neume Component" selection, select the whole pes and move it up and to the right; you'll see the puncta change order. Then move it back to its correct position, and then away again; the puncta will change back. This happens consistently every time the neume is moved in this manner, even though the puncta haven't moved in relation to each other.
- The mainly orange neume on the second staff, over the syllable "ve-" --> If you group it as we usually do, first with "Neume" then "Neume Component," you'll see in the Info section that the neume components are ordered wrong. Using the "Neume" selection, move the neume away, then back again; that corrects the order.
- The mainly blue neume farther along the second staff, over the syllable "tu-" (right before the fancy letter) --> Following the same process as the previous point produces the same result; the neume components are ordered wrong, but if you move the neume away and back the order is corrected.

Hope this is useful!

**Comment by annamorphism** [comment]
@JoyfulGen I still can't seem to reproduce the issue with the pes... The problem with the other neumes is that, before grouping, some neumes are "inserted" into others (e.g. the orange torculus stretches across the other two neumes) but the neume grouping attaches the neumes from left to right (so a similar issue to #680 and #657). One fix would be to check the coordinates of the neumes every time they are grouped (which seems to be what happens when you move them back and forth), so that they automatically end up in the right order without additional action from the user.

**Comment by annamorphism** [comment]
update: I managed to reproduce the pes problem (it's also true of the pes inside the syllable "em"). Both puncta in the affected pes have the same ulx value, and it seems like they are being ordered randomly (for me it's not strictly alternating--I don't think it has to do with where you move it). Solution: puncta with the same ulx value should be consistently ordered bottom to top, so high uly to lower uly.  This should consistently give you pes when they are pes, and not when they are not. (Unless there is some sort of extreme diagonal skew on the original image, but that would be a different problem.)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes. Could you please help me test it and confirm that the issue is solved and close it?

**Comment by JoyfulGen** [comment]
I tested the fix in folio 005r and corrected all of 005v and the issue didn't come up once! I'm therefore going to close the issue. Thank you @yinanazhou!
