### ISSUE TITLE
Incomplete ungrouping of a neume involving an oblique

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#724]
In browser Neon, ungrouping a neume with an oblique in it results in the oblique staying grouped with the first punctum of the neume. This situation happens when a neume contains an oblique with at least one punctum preceding it (if the oblique is the first component of the neume, there's no issue). From what I can tell, the issue is systematic; no matter how many neume components are before the oblique, it always stays grouped with the first punctum. 

Some demos, in which you can tell that the oblique is grouped with the punctum because a) they're the same colour and b) if I select one, the other one gets selected as well:

https://user-images.githubusercontent.com/83373378/138095296-1ded7558-1761-48a0-93e9-42b95cdb87c4.mov

https://user-images.githubusercontent.com/83373378/138095306-5cd1b443-93f4-474a-bfa1-8186f63e6d0c.mov

The second example shows that ungrouping the oblique and the punctum doesn't work. The only solution is to delete one of the glyphs and input it back in.

**Comment by JoyfulGen** [comment]
This issue also happens in rodan staging, but not in rodan2.

**Comment by annamorphism** [comment]
In what might (?) be a related issue, ungrouping certain neumes with ligatures (those where it is the first component) makes all the components merge into one/disappear. Like so:
![image](https://user-images.githubusercontent.com/67451875/141530926-ad41b2be-2dc9-430e-8e92-8f243e797df8.png)
![image](https://user-images.githubusercontent.com/67451875/141530907-36f4c3b8-55a6-4833-b130-b9025f69c651.png)

**Comment by yinanazhou** [comment]
Hi @annamorphism , I just checked about this issue. Just to confirm, does it only happen to neumes that start with a ligature?

**Comment by annamorphism** [comment]
Correct. When the ligature is elsewhere it behaves as expected: 
![image](https://user-images.githubusercontent.com/67451875/141533640-431a9843-527b-41e5-93f5-d5ba2156f5bb.png)
