### ISSUE TITLE
Divisios don't align with the staff (aesthetic issue)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#735]
If a staff isn't horizontally straight (which is often the case, since the staves follow the slant of the page), the divisios I put on it don't align. It looks like the divisios are staying on an imaginary perfectly straight staff, so that when the actual staff slants down, the divisios don't follow. Demonstration:

https://user-images.githubusercontent.com/83373378/144857257-781a87eb-03d3-450d-9f27-0b6cb48e0941.mov

This is really just an aesthetic issue, because the vertical placement of the divisios in Neon doesn't influence the MEI.

**Comment by yinanazhou** [comment]
The issue has been solved in merge #737. I will close this issue. Please let me know if it needs further adjustment.
