### ISSUE TITLE
Neon can't render two obliques in a row within the same neume

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#741]
In Einsideln, there are neumes such as the little monster below (folio 005r) where two obliques are stuck together. (I don't think there are any of these in Salzinnes, which is why the issue has never come up.)
<img width="81" alt="Two obliques in a row" src="https://user-images.githubusercontent.com/83373378/148076223-9388a540-2d04-44d1-84b5-74794f7cf7df.png">

I tried to input it in Neon as I saw it, but Neon didn't like that at all. The first oblique I can toggle just fine, but when I try to toggle the second one the first oblique disappears and the neume goes a bit wonky. An illustration:
https://user-images.githubusercontent.com/83373378/148076297-8c08a4f8-5d13-45a9-a60b-4220c452745b.mov

I tried it in different places in the folio and the result was always the same.

Here's the MEI snippet of the neume before trying to toggle the ligature. The pitches are all in the correct order:
```
                                    <neume xml:id="neume-0000000050224170">
                                        <nc xml:id="nc-0000001485719275" facs="#zone-0000000964850695" oct="2" pname="f"/>
                                        <nc xml:id="nc-0000000244663120" facs="#zone-0000000173739064" oct="2" pname="e"/>
                                        <nc xml:id="nc-0000001298664128" facs="#zone-0000000457068665" oct="2" pname="f"/>
                                        <nc xml:id="nc-0000000182999719" facs="#zone-0000000625996637" oct="2" pname="d"/>
                                        <nc xml:id="nc-0000001132342010" facs="#zone-0000001030298184" oct="2" pname="e"/>
                                    </neume>
```
And here's the snippet of the neume after trying to toggle the second ligature. The pitches are in the completely wrong order, which explains why Neon is having trouble rendering the obliques. It also looks like one of the E's has become a D, even though I did nothing to change the pitches.
```
                                    <neume xml:id="neume-0000001795977336">
                                        <nc xml:id="nc-0000001169066819" facs="#zone-0000001185638847" oct="2" pname="f" ligated="true"/>
                                        <nc xml:id="nc-0000001864200944" facs="#zone-0000000114669321" oct="2" pname="f" ligated="true"/>
                                        <nc xml:id="nc-0000000549207912" facs="#zone-0000000935834058" oct="2" pname="d" ligated="true"/>
                                        <nc xml:id="nc-0000001844173757" facs="#zone-0000001562261573" oct="2" pname="d" ligated="true"/>
                                        <nc xml:id="nc-0000001725552713" facs="#zone-0000000748656993" oct="2" pname="e"/>
                                    </neume>
```
These are the files I'm working from:
[005r_pre-toggle.mei.zip](https://github.com/DDMAL/Neon/files/7808391/005r_pre-toggle.mei.zip)
[005r_post-toggle.mei.zip](https://github.com/DDMAL/Neon/files/7808392/005r_post-toggle.mei.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed changes. Now Neon can display more than one obliques within the same neume. The change in the order of the neume components is because Neon sorts neume components by the x coordinate, and in this neume, after toggling, the first neume component in the second oblique is on the left of the second neume component in the first oblique. This part of the issue will be solved in issue #713. Could you please test the display of more than two obliques in the same neume is working well? If so, please close this issue.

**Comment by JoyfulGen** [comment]
I can confirm that Neon can now display two obliques in a row in the same neume! Exhibit A:
<img width="95" alt="Two obliques in a row fix" src="https://user-images.githubusercontent.com/83373378/148392053-7e79d895-f478-458e-ae11-09545b51ff2c.png">

However, the neume looks good as long as I don't touch it anymore. Moving either a part or the whole of it makes it go wonky again:

https://user-images.githubusercontent.com/83373378/148392181-968961b5-13ce-4c61-a92f-d1146b10b3d5.mov

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've just pushed the changes. Now you should be able to have more than one oblique in a neume and move them as you like. Please close this issue if it functions well. Thank you!

**Comment by JoyfulGen** [comment]
Everything works perfectly! Closing the issue now.
