### ISSUE TITLE
ungrouping neumes lose components

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#745]
Some neumes seem to delete neume components when ungrouping; for example, the pink neume below, when ungrouped, loses several component neumes (and the two remaining components are still grouped as pink!). 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/67451875/148477834-f6fb1ea2-25af-4392-93a5-d73226080335.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/67451875/148477991-3078591e-14f4-4ede-9dd4-2526b18327d2.png">

In the MEI file, two of the components have a "false" ligature marker, which seems to contribute to the problem.  
Before ungrouping:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/67451875/148478218-3043036a-3a20-40cd-9d9e-ea11c0cd106a.png">

and after: 
<img width="982" alt="image" src="https://user-images.githubusercontent.com/67451875/148478335-a7ea4980-17dc-4c81-8fe2-a340c12a7e6f.png">

**Comment by yinanazhou** [comment]
Hi @annamorphism, I couldn't reproduce this issue. But I did notice a potential ungroup issue when `ligated="false"`. I have fixed it and pushed the changes. Please let me know if this issue is solved in the latest merge.

**Comment by annamorphism** [comment]
@yinanazhou the original issue now seems to be resolved! But now something about ligated="false" seems to be triggering an issue like #641 again.

**Comment by yinanazhou** [comment]
Hi @annamorphism, I have pushed the changes. Could you please test it and close both issues if it is successfully solved? Thank you!

**Comment by annamorphism** [comment]
Yes, it seems to be solved! closing issue.
