### ISSUE TITLE
Request for a neume-splitting tool

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#759]
This is sort of related to https://github.com/DDMAL/Neon/issues/694. That issue is still open, but in my comment I mentioned that the drop-down neume menu could be a useful feature for splitting neumes in two. At the moment, splitting a neume in two requires us to ungroup the entire neume and then group the neume components of the neumes we want. Here's an illustration of that:

https://user-images.githubusercontent.com/83373378/151828564-7208b17a-98ec-476f-8e83-64a8482c2ff8.mov

@thesoundbyle and @annamorphism suggested that a better fix for that would be to have a sort of razor tool, where one could click anywhere in the neume and it would split at that spot (a similar function already exists to split staves). I think they're correct! It would save a significant amount of clicking and be more straightforward than the drop-down neume menu.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the new feature about this. Could you please test it? Let me know if anything needs a fix! Thank you.

**Comment by JoyfulGen** [comment]
I'm on it! Update coming soon.
