### ISSUE TITLE
Toggled syllables remain partially toggled when interacted with, results in very strange behaviours

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#783]
It's easiest I think to explain this with an example of a strange behaviour:

In folio 271r, there's a big syllable on staff one (syllable 1) toggled with a big syllable on staff two (syllable 2) (the OMR here is sort of a disaster, please do not be alarmed). Exhibit A:

<img width="820" alt="271r toggled syllables 1 and 2" src="https://user-images.githubusercontent.com/83373378/158651069-82d9406c-9601-4088-b964-ea8e2eb39ab5.png">

If I select either one, I can untoggle them and everything behaves as expected; both syllables lose their `follows`and `precedes` elements and syllable 2 gains its very own `syl` element.

The problem arises if, without untoggling the syllables, I add a punctum to syllable 2 and merge it with another to create a pes. That automatically separates it from the green syllable and it becomes its own little yellow syllable, syllable 3. Exhibit B:

<img width="827" alt="271r created syllable 3" src="https://user-images.githubusercontent.com/83373378/158651127-71bcc9ee-3e07-4c09-a9a7-b29c485671b8.png">

Then weird things happen with the toggles. The new pes gains a `syl` element, but also keeps its `follows` element, so it's still toggled to syllable 1. Syllable 1's `precedes` element now only refers to syllable 3. Meanwhile, syllable 2's `follows`still refers to syllable 1. So syllable 1 is fully toggled to syllable 3, and partially toggled to syllable 2. Exhibit C:

<img width="901" alt="271r toggling weirdness" src="https://user-images.githubusercontent.com/83373378/158652557-16b73209-5ff5-444c-b8bb-58c11c26b470.png">

This leads to many weird situations that are very hard to figure out and get out of. I discussed this with @annamorphism and we think the best solution would be the following: if a user interacts with a toggled syllable in any way, all involved parties (except the user, ha) automatically become fully untoggled: they lose their `follows` and `precedes` elements and get a `syl` element. Interactions include changing the neume groupings, adding and deleting neumes, and merging neume components with other/new neume components. We're pretty sure that if that fix is implemented, all other issues resulting from this will go away.

This issue is quite urgent, because toggled syllables are common and it's pretty easy to create the strange phenomenon detailed here. A temporary solution is to make sure to untoggle everything in the file before doing anything else.

The MEI files:
[271r before any interaction.zip](https://github.com/DDMAL/Neon/files/8266889/271r.before.any.interaction.zip)
[271r after grouping the punctum.zip](https://github.com/DDMAL/Neon/files/8266890/271r.after.grouping.the.punctum.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @annamorphism , I have merged the changes to automatically untoggle linked syllables when grouping neumes inside them. Also, a new `bbox` will be assigned to the second syllable. Please let me know if everything works as expected. Thanks!

**Comment by JoyfulGen** [comment]
It works very well so far! Will update you after correcting complete folios.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please confirm that this issue can be closed?

**Comment by JoyfulGen** [comment]
I've encountered no problems, everything works very smoothly. Closing the issue now.

**Comment by JoyfulGen** [comment]
@yinanazhou I'm reopening this issue because some of these weird toggling issues are happening again. The fix to this issue was that if any part of a toggled syllable was interacted with in any way, all involved parties automatically became untoggled, lost their `follows` and `precedes` tags and acquired, where applicable, a `syl` element. This is currently not happening. Here are some examples:

**Example 1**
1. Toggle a one-neume syllable at the end of a staff with the one-neume syllable at the beginning of the next staff;
2. Add a punctum to the first syllable and group neumes and neume components;
3. The second syllable retains its `follows` tag and doesn't get a `syl`.

**Example 2**
1. Toggle a two-neume syllable at the end of a staff with a one-neume syllable at the beginning of the next staff;
2. Add a punctum to either one of the first neumes, grouping neumes and neume components;
3. The neume you interacted with becomes its own syllable and untoggles itself, but the remaining syllables remain toggled.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @annamorphism I've been playing around with the linked syllables. The best solution might be to make the user cannot interact with linked syllables unless they are unlinked first. We have two ways of doing this:

1. Any selections involve linked syllables will only be given the `toggle linked syllables` option.
2. The `group`/ `ungroup` option will appear, but if the user click on them, the user will get a warning saying the action cannot be done because of a linked syllable.

I've implemented the first option already, but after testing I think it may confuse the user because it does not provide any hints why I cannot group/ungroup them. Please let me know what you think! Thanks.

**Comment by yinanazhou** [comment]
This issue has been fixed by https://github.com/DDMAL/Neon/pull/1122 and https://github.com/DDMAL/Neon/pull/1123. @JoyfulGen could you please confirm that we can close this issue?

**Comment by JoyfulGen** [comment]
Confirmed! Re-closing issue.
