### ISSUE TITLE
Divisio is duplicated when I... move a neume? (details still missing)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#786]
In folio 270v, syllable "bam" has two divisios in it right out of OMR; one at the beginning, and one at the end. For some reason, when I move the first divisio towards the neume, a duplicate is created on the staff above it and Neon loses its mind. Here it is:

https://user-images.githubusercontent.com/83373378/159295054-3e6d3ac3-3add-4b3d-b4a4-c49e9d72c5c0.mov

For some reason, the consequence of this is that I can't delete any glyph on the page. I can select the glyph, but when I click delete nothing happens.

This is the MEI snippet of the syllable in question:

<img width="832" alt="270v weird syllable" src="https://user-images.githubusercontent.com/83373378/159295390-6ae0592c-11f3-4758-841a-41c13a68a35a.png">

And the MEI files before and after:
[270vbefore.mei.zip](https://github.com/DDMAL/Neon/files/8316743/270vbefore.mei.zip)
[270vafter.mei.zip](https://github.com/DDMAL/Neon/files/8316744/270vafter.mei.zip)

I can't figure out what's different about this syllable that's making it behave this way. I can, however, reproduce this specific issue every time.

**Comment by yinanazhou** [comment]
I've looked into it. It seems that Neon duplicated a divLine above the original divLine, and the two share the same @xml:id, so it reports a validity error. I'm still trying to figure out what triggered this behaviour. It does not happen to other divLines.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I think I've found what triggered this weird behaviour. This happens when the `divLine` or `accid` is inside the syllable and when I drag it to a different staff. Could you please test and confirm this?

I do notice that in the case of 270v, this issue happens when the staff is not changed. But I will solve the above case first, and see if the case in 270v is solved. Does this sound good to you?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. I added a check to the Drag action. When you move a divLine or an accid, Neon will check whether the element is still in the syllable's x-range. The syllable's x-range is defined as the upper left x of the first nc to the lower right x of the last nc in the syllable. If the element is not in this range, Neon will move the element outside of the syllable. 

A special case is when the syllable only contains one neume. In this case, there is no way for the element to be inserted into the syllable (the element only goes between the neumes). The element will be moved out of the syllable, unless inserted between the nc, which does not really happen (do we need to check whether the position of a divLine or an accid is in a nc?)

I've tested a few cases. It works fine. But in the example you provided above, when the divLine is moved to a different position, it jumps to the staff above. I'm not really sure why the jump happens. But after the jump, you can move it to other places as you wish, and it does not cause an error anymore.

Could you please test it further and confirm that this is solved? Thanks!

**Comment by JoyfulGen** [comment]
Hi @yinanazhou, I tested the changes. I can confirm that if I move a divLine out of its syllable, Neon moves it outside of the syllable. However, this only works if I move the divLine out of the x-coordinate range of its syllable. If I move it directly above or below, it duplicates and creates the issue above. If I move it back, the duplicate disappears, but the file remains invalid. Would it be possible to add a staff check as well, so that if the divLine is moved to another staff it's also moved out of its syllable?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, sure! I see where I missed. Will solve it tonight.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please confirm that this issue can be closed?

**Comment by JoyfulGen** [comment]
Yes, it works perfectly now! Closing the issue.
