### ISSUE TITLE
First syllable sometimes lacks bounding box

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#790]
It sometimes happens that when I upload a new folio, its first syllable has no text and no bounding box. Usually, adding text makes an invisible bounding box appear, but in this case it does not. I don't know why this happens, but I know what the MEI looks like, so here it is:

Folio 264r is an example of this situation. Before uploading the file to Neon, the coordinates of the bounding box of the first syllable are all 0.
<img width="543" alt="264r BB all 0" src="https://user-images.githubusercontent.com/83373378/160635525-00f508e7-944e-446d-9b22-94a47e6467c2.png">

After uploading the file to Neon and adding text to the syllable, the syllable in the MEI has a `syl` with the input text, but the coordinates of the bounding box aren't listed at all.
<img width="575" alt="264r BB nothing" src="https://user-images.githubusercontent.com/83373378/160635805-aeea6a2c-d6cb-45be-b1db-17dd6b61f751.png">

This issue also happens in 264v and the MEI looks the same. Here are the files:
[264r.mei.zip](https://github.com/DDMAL/Neon/files/8372407/264r.mei.zip)
[264v.mei.zip](https://github.com/DDMAL/Neon/files/8372410/264v.mei.zip)

The only fix is to delete the neumes and input them back in. I'd estimate this issue occurs in one out of three folios, but it isn't super urgent, because it only applies to a single syllable per folio.

I still don't know the unifying factor between the folios where this happens, but I'll keep looking!

**Comment by jinh0** [comment]
Huh, that is weird. I am able to replicate the bug. I see that when you download the edited file, the text is there but not shown on Neon. I will look into it further.

**Comment by jinh0** [comment]
Since the coordinates themselves are all 0's before the file is uploaded to Neon, this is not an issue with Neon. Verovio, after seeing 0,0,0,0 deletes the coordinates entirely because it is not technically a bounding box.

**Comment by JoyfulGen** [comment]
Since this issue is an mei_encoding one, I'm going to close this one.
