### ISSUE TITLE
Obliques misbehave when grouped

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#792]
Sometimes, when I add puncta to an existing oblique (straight-outta-OMR), when I group the neume components the oblique goes wonky:

https://user-images.githubusercontent.com/83373378/162229399-e7ea7c80-8d37-4a2a-83a5-1c382123a572.mov

When this happens, using the neume selector to drag the oblique away fixes it instantly. You can then drag it back to its correct position and it's perfectly happy. So the fix is pretty simple, but it's still a strange anomaly.

From what I can tell, the distinguishing factor between obliques that misbehave and obliques that don't has to do with the way the `facs` is expressed (is that the right word? I dunno. Moving on). In almost all cases, including the normal obliques, the `facs` looks like this:

<img width="832" alt="261r no zones" src="https://user-images.githubusercontent.com/83373378/162230224-1f6daffb-eb77-4647-912a-e9635377699b.png">

But with obliques that misbehave, it looks like this:

<img width="862" alt="261r zones" src="https://user-images.githubusercontent.com/83373378/162230354-f13583a5-8228-4231-8393-221211db968a.png">

It looks to me like the only times that "zone" appears is in misbehaving obliques. But I don't know why it's there.

Here's the file straight outta OMR: [261r.mei.zip](https://github.com/DDMAL/Neon/files/8444128/261r.mei.zip)
And here it is after I grouped the nc's in that oblique (syllable "wonky"): 
[261raftergroupingnc.mei.zip](https://github.com/DDMAL/Neon/files/8444142/261raftergroupingnc.mei.zip)

**Comment by yinanazhou** [comment]
Update: I can reproduce the issue when the inserted ncs are in the same position as shown in the video (one before the oblique, and one after the oblique). One interesting thing is, if I only insert one before, or only insert one after, the issue doesn't happen. The issue may happen in the method where verovio determines which nc is the first nc of the oblique.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the fix for this issue. I've tested with the example you provided, and the issue seems fixed. Could you please confirm and close this issue? Thanks!
