### ISSUE TITLE
Clef inserted in wrong place in MEI 

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#802]
When the glyph at the beginning of a staff isn't identified as a clef in the OMR, there's a `<custos>` and an `<sb>` element in the MEI, but no `<clef>` element. This is fine, because the pitches of the neumes are determined with the default clef on the third line from the bottom and once the user adds a clef, the pitches are reevaluated if necessary. 

However, it happened three times in Einsie 253r that when I inserted the clef, it went very much in the wrong place in the MEI. Here's a pic to make that clearer--though the symbol of the clef in Neon is clearly in the correct place, in the MEI the `<clef>` line is actually where the arrow is pointing:

<img width="852" alt="253r clef in wrong place" src="https://user-images.githubusercontent.com/83373378/167466052-92ec1655-7a4b-44c8-ae11-2498bcd54868.png">

In the MEI, the syllables on that staff that are before the arrow are therefore after the staff break, but before the clef. The consequence of this, as is visible in the above screenshot, is that if I then insert new neumes between where the clef should be and where it actually is, they dutifully go after the `<clef>` in the MEI, which makes the order completely wrong. As an illustration, if you keep your eye on the Text Info box, you'll see the text isn't in consecutive order, even though the syllables I'm selecting appear to be:

https://user-images.githubusercontent.com/83373378/167466053-2fcc2463-7734-42ed-a5ab-958b6af8a256.mov

I think this may be connected to DDMAL/Rodan#634, because this only happened in places where there was no clef and where the `<custos>` and an `<sb>` were inside the syllable. I don't know why the clef went where it went. To be continued.

Here's the MEI file straight-outta-OMR:
[253rvSOOMR.mei.zip](https://github.com/DDMAL/Neon/files/8653935/253rvSOOMR.mei.zip)
And here's the MEI file once I've corrected all the neumes and grouped the syllables correctly (syllables out of order are emphatically labeled "NO"):
[253rsyllablesgrouped.mei.zip](https://github.com/DDMAL/Neon/files/8653936/253rsyllablesgrouped.mei.zip)

**Comment by annamorphism** [comment]
@JoyfulGen does the clef always end up at that same spot in "domini" no matter where you tried to put it? or does it go somewhere at random?

**Comment by JoyfulGen** [comment]
Thank you @annamorphism! Thanks to your excellent question, I think I've found an important clue. 

To answer said excellent question, the clef does end up in the same spot in "domini" every time I insert it. Turns out, that's because there's a straight-outta-omr (SOO) syllable in that word that the clef seems to be irresistibly attracted to. I checked the other place in the folio where that issue occurs and it's the same thing!! In the MEI, the clef is inserted after the SOO syllable. If I delete the empty syllable before inserting the clef, the clef goes where it's supposed to go and everything is fine. @yinanazhou do you know why this could be?

**Comment by JoyfulGen** [comment]
Thanks to the new function that deletes empty syllables before correction, this isn't a problem anymore. Closing issue now.
