### ISSUE TITLE
Saving user's display settings on localStorage

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#804]
It would be very convenient if every time I refresh the page, my display settings from my previous session, such as the zoom level and displaying text, persisted to this new session.

EDIT:

List of settings to be saved in localStorage:
- [x] Zoom setting
- [x] Glyph opacity
- [x] Image opacity
- [x] Highlight options
- [x] Display settings (bounding box, text, info)
- [x] Selection mode
- [x] Viewbox (user's position on the SVG)
- [ ] Save whether the user was last in insert mode or edit mode
- [ ] Insert option

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for local storage. Please let me know what you think about this new feature!
