### ISSUE TITLE
Fix zoom slider.

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#818]
## Issue Description
Whenever I load the website and zoom in, I enter into a game of Russian roulette with whether Neon is going to be unresponsive or not.

I know I need to wait some period of time before I can zoom in, but it does not make sense that the zoom controls even shows up at all and **responds to my input** if it is not ready.

Either the zoom slider should be disabled (visually and functionally) until it is ready, or the zoom slider should ignore any user input until it is ready.

Also, Zoom.ts is incomprehensible for the most part due to bad variable naming.

## Relevant Images
![Screen Shot 2022-05-13 at 11 47 37 AM](https://user-images.githubusercontent.com/40512164/168320178-fd7be25f-c6b7-4fe3-80b8-c5f1f2a5245b.png)
.
![Screen Shot 2022-05-13 at 11 48 39 AM](https://user-images.githubusercontent.com/40512164/168320553-ea7102a8-8deb-4d06-9479-eb533b3ca7e4.png)

## How to Replicate
Reload Neon and move the zoom slider within a second or so of loading.

**Comment by jinh0** [comment]
This is still an issue, and can be fixed alongside some other issues we are trying to solve.

**Comment by yinanazhou** [comment]
> This is still an issue, and can be fixed alongside some other issues we are trying to solve.

Could you please explain what the issues are?

**Comment by jinh0** [comment]
The core issue was that zoom was able to be changed before the SVG loaded, which caused not just this issue but also localStorage changes to zoom, glyph opacity, and image opacity to not work. They have now all been fixed in the localStorage PR #907. Fixed in this commit: eecf379a2cf22d3f0e1b26b38b388978e00ac922
