### ISSUE TITLE
disappearing accidentals

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#824]
Moving some accidentals causes them to disappear. Weirdly, this doesn't seem to affect accidentals I've inserted--only ones that were there already on uploading. 

https://user-images.githubusercontent.com/67451875/168691496-1b9a9348-437b-45bc-93fa-c8f657f1dad8.mov

https://user-images.githubusercontent.com/67451875/168691999-6f97c445-878d-4880-bc61-871c83381d0d.mov

**Comment by annamorphism** [comment]
on further investigation, they don't disappear entirely, they just sort of skedaddle to somewhere else on the page: 
![image](https://user-images.githubusercontent.com/67451875/168692972-5b724c5d-2438-4f01-9d78-87f8df3bb30e.png)
They like it there, too; any time you try to put them elsewhere, they return to the lowest staff (but at the x-coordinate you chose).

**Comment by annamorphism** [comment]
turns out the divisios like to have a little party on the lowest staff too! 
![image](https://user-images.githubusercontent.com/67451875/168693661-f84871f3-6aac-45d4-8936-eb59c7b32f5b.png)

**Comment by jinh0** [comment]
Huh, that is a strange bug indeed. I'm not able to replicate this bug, can you send me the folio you're working on?

**Comment by annamorphism** [comment]
This is folio 001r; I think it should be the same as the one currently in the "reviewed" folder.

**Comment by annamorphism** [comment]
Seems to not be limited to that folio; just tried uploading 4r and it behaves the same way
[CH-E_611_004r.mei.zip](https://github.com/DDMAL/Neon/files/8711604/CH-E_611_004r.mei.zip)
.

**Comment by jinh0** [comment]
I can replicate it now! Will look into it :)

**Comment by jinh0** [comment]
Hi @annamorphism it seems like the MEI file itself is the issue?

The accidental in the MEI file that you gave me has a y-coordinate of 28517, way out of range of the normal height. This might explain why it keeps dropping down to the bottom.

![Screen Shot 2022-05-18 at 11 26 16 AM](https://user-images.githubusercontent.com/40512164/169080908-bbf44ba8-70fb-4e86-8e80-86798a4430c7.png)

**Comment by yinanazhou** [comment]
Looks like this is in verovio.

**Comment by annamorphism** [comment]
@jinh0 Not a bad idea, though I wonder why these accidentals are showing up so far out of bounds in the first place. @JoyfulGen have you encountered this? 
Also, even if the accidental is initially out of bounds, why isn't moving it creating a new (presumably in-bounds) y-coordinate for it?

**Comment by yinanazhou** [comment]
> I can only reproduce this issue in the early files I corrected, but it doesn't seem to be happening anymore. @yinanazhou, is there some property of flats and divisios that could've changed since you first implemented them that would explain this issue being fixed?
> 
> Edit: after further investigation, it looks like the cutoff is 004v; folios before it have skedaddling accidentals, folios after it don't. If it can be helpful, I finished that folio on December 17.

Ohhh yes! The cause is the same. The mei files may save the wrong coordinates before the issue is fixed.

**Comment by JoyfulGen** [comment]
It's confirmed that the issue has been fixed! @annamorphism, are you ok to close it?

**Comment by annamorphism** [comment]
Closing this issue!!
