### ISSUE TITLE
Inserting an accidental into a syllable makes the MEI file invalid

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#829]
If an accidental is the child of `syllable`, the MEI file is invalid. This is true whether the flat is in the syllable in the straight-outta-omr file, or if it's manually inserted in the syllable by the user. 

At the moment this isn't a huge problem, because flats are rare enough that deleting the problematic ones and putting them back in isn't too time-consuming. Long-term it would still be useful to avoid this issue though.

(This issue was briefly mentioned in https://github.com/DDMAL/Neon/issues/762, but I closed that issue because it too long and it was about divisios anyway.)

**Comment by yinanazhou** [comment]
This issue has already been fixed with the current MEI schema we are using.

**Comment by JoyfulGen** [comment]
What!?!?!? What excellent news!!! I didn't realize and I'm delighted :))
