### ISSUE TITLE
Request to add a button that allows the user to insert a clef into the nearest syllable

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#840]
This issue is the proposed solution to https://github.com/DDMAL/Neon/issues/650.

Clefs are almost always a child of layer, but there are rare instances where a clef appears in the middle of a syllable. For example:

<img width="948" alt="061v clef inside - folio" src="https://user-images.githubusercontent.com/83373378/170033752-7bb0c47b-2fe4-4573-8f15-683cc03c631a.png">

<img width="1161" alt="270v clefs example" src="https://user-images.githubusercontent.com/83373378/170034135-c919d897-3dc3-4faa-b665-11a57f6de831.png">

At the moment, it's impossible to insert a clef into a syllable in Neon. Visually, the clef can be in the right place, but in the MEI the clef gets added at the end of the syllable, so the pitches that are supposed to be after it are wrong (this is also detailed here https://github.com/DDMAL/Neon/issues/650#issuecomment-1031680528). 

The request, therefore, is to have an "Insert to nearest syllable" button like the one that appears for divisios and accidentals appear for clefs as well. We don't think that the process of adding a clef into a syllable should be automatic; clefs in the middle of syllables are rare enough that allowing the user to insert the clef into the nearest syllable when needed will be perfectly adequate.

**Comment by chetbae** [comment]
https://user-images.githubusercontent.com/48145854/180144746-ed2142de-02bf-44e1-8dfb-4cc197a366d9.mov

Just checking that this is the expected behaviour for clef being inserted and moved out of syllables @JoyfulGen?

Play-by-play:
- target syllable has pitches relative to preceding clef
- clef-being-inserted is inserted and highlighted if in syllable selection
- divLine is inserted and highlighted if in syllable selection
- neumes following inserted clef reflect pitches relative to inserted clef
- neumes preceding inserted clef do not change
- move clef and divLine out of syllable
- syllable has pitches relative to preceding clef

**Comment by JoyfulGen** [comment]
This is awesome!! I particularly like the addition of clefs and divisios taking on the syllable colour if they're part of it. This will  be incredibly useful, thank you!

**Comment by chetbae** [comment]
@JoyfulGen @annamorphism One more thing!

Suppose a clef is inserted into a syllable. When dragging the syllable, how should the clef behave after the syllable is in a new position? For example, maybe the clef should move with the syllable left or right, but maintain the same line in the staff. Or, move with the syllable and snap to the closest line when dropped?

**Comment by annamorphism** [comment]
@chetbae I think I like the first option better, so the clef's line stays the same. @JoyfulGen what do you think?  I feel like moving a syllable with a clef in it doesn't come up too often.

**Comment by JoyfulGen** [comment]
@chetbae @annamorphism I agree, I prefer the first option as well. Once the clef is on the correct line, it's easiest for the corrector if it stays there!

**Comment by chetbae** [comment]
https://user-images.githubusercontent.com/48145854/180944905-a1bd0e55-6097-42e7-bf9b-8a9c885aec61.mov

Woohoo changes incoming @yinanazhou

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @chetbae, I've pushed the changes for the clef insertion. We have one minor issue to fix, but I pushed it anyway so that Gen can also test it. 

The issue is, when you ungroup the syllable with a clef, the neumes after the clef will jump to where the first nc is on the C line (the exact position needs more testing).

@chetbae, I've changed a few variables' names, please check if they make sense.

**Comment by JoyfulGen** [comment]
Hi @yinanazhou and @chetbae, this is such a useful fix!! I can insert a clef (or two!) in a syllable and the pitches change accordingly. When I move the syllable around, the clef stays on its pitch, which is FANTASTIC. I can also toggle syllables that contain clefs now! I'll be able to fix many folios, this is great. 

I do see the issue you mentioned; what's happening is the neumes after the inserted clef are trying to keep the same pitch, but they don't recognize the inserted clef anymore, so they jump to maintain the same pitch but with the previous clef. You can see this clearly if you move the previous clef to another line, because the neumes will jump differently. 

I've noticed another small issue with the inserted clef: if I insert a clef into a syllable and then try to merge that syllable with another one, the merge happens, but the clef becomes its own syllable, with bounding box and text nugget. Here's a demo:

https://user-images.githubusercontent.com/83373378/183076258-db975731-da81-4daa-9c11-26d44daa6b8c.mov

This is the MEI file: [271r clef in syllable.mei.zip](https://github.com/DDMAL/Neon/files/9268517/271r.clef.in.syllable.mei.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for the merging issue mentioned above. Please let me know if it works. Thanks!

**Comment by JoyfulGen** [comment]
The merging issue is fixed! I've found another issue though, which I _think_ is new, illustrated below:

https://user-images.githubusercontent.com/83373378/193270168-bd064abb-120a-4c09-a0c3-9e03ab367878.mov

Basically, when a clef is inserted in to a syllable, the neume following doesn't stay where I put it. It also moves downwards every time I move the neume before the clef. If I use the syllable selector, the neume on the left of the clef stays where I put it and the clef jumps back to where it was (this is expected and desired behaviour), but the neume after the clef jumps down.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for the dragging issue. Please let me know if it works. Thanks!

**Comment by JoyfulGen** [comment]
The dragging issue is fixed! I tried moving different parts of the syllable around using the neume/neume component/syllable selector and everything works well. The only thing left now is the jumping neume issue; when you ungroup a syllable containing a clef, the neume(s) after the clef automatically jump to the line or space they have to be on to maintain the same pitch. (This is how I explained it in a previous comment: _I do see the issue you mentioned; what's happening is the neumes after the inserted clef are trying to keep the same pitch, but they don't recognize the inserted clef anymore, so they jump to maintain the same pitch but with the previous clef. You can see this clearly if you move the previous clef to another line, because the neumes will jump differently._) @annamorphism, do we care?

**Comment by JoyfulGen** [comment]
Ok, so I think everything in this issue is fixed! Closing it now.
