### ISSUE TITLE
Merging a syllable containing a divisio makes that divisio into its own syllable

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#841]
Here's a demo: The blue syllable contains a divisio. If I merge it with the orange syllable following, the divisio in question becomes its own syllable, without a `syl` element. We know it's there, because the blue colour is suddenly missing. Deleting the divisio using the "Neume component" selection makes the `divLine` element go away, but the syllable remains. Undoing that action makes the divisio return, now with its own bounding box!

https://user-images.githubusercontent.com/83373378/170037914-a56c5941-c096-4456-8123-d0814e205da2.mov

This is the syllable containing the divisio in the straight-outta-OMR file:
<img width="835" alt="252v bloop before intervention" src="https://user-images.githubusercontent.com/83373378/170038392-c87f204e-6d02-48be-bfe4-d7ed0e9dddbb.png">

This is after I've merged that syllable with the syllable following--the divisio is now its own syllable
<img width="833" alt="252v bloop after merge" src="https://user-images.githubusercontent.com/83373378/170038426-3adea62c-fe08-4b70-a956-dafe5780d7f7.png">

And this is after deleting the divisio, with the lonely syllable remaining:
<img width="834" alt="252v after deleting divisio" src="https://user-images.githubusercontent.com/83373378/170039618-64141169-95a7-4772-9fea-ce772a8c8488.png">

I think the best solution would be to make so that when a syllable containing a divisio is merged, that divisio automatically becomes a child of `layer`.

A couple extra notes:
- This issue occurs whether the divisio is at the beginning, in the middle, or at the end of the syllable being merged.
- If, after merging, I delete the divisio-syllable using the "Syllable" selection, the entire syllable disappears in the MEI.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for this issue. Now when you group syllables that contain divLine or accid, they will be inside the new syllable. Please let me know if you noticed anything unexpected. Thanks!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, we will add a new button that can move layer elements out of a syllable. For now, you can use ungroup to move them out. Sorry for the inconvenience.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've added the button that can move divLine/accid out of a syllable. If they are inside a syllable, the `Move out of syllable` button will be available. And if you move them far away (near to another syllable), they will be moved out of that syllable and become a child of layer.  If they are outside a syllable, the `Insert into nearest syllable` button will appear. Please let me know if anything unexpected happens or if you have more wonderful ideas about this button!

**Comment by yinanazhou** [comment]
@JoyfulGen, sorry about the confusion! I've pushed the changes! should work now!

**Comment by JoyfulGen** [comment]
It does work! Closing the issue now.
