### ISSUE TITLE
Request to allow for accidentals to be anywhere on the staff, not just top line

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#852]
This is related to the last comments in issue https://github.com/DDMAL/Neon/issues/661. Accidentals have now been implemented, but they only ever live on the top line of the staff. This is @annamorphism's comment: 

"@yinanazhou does it help to know that in virtually all cases, the accidental should be on the pitch B/B-flat? In some cases this alone will be unambiguous, but just in case, the nearest neume on a B should clear things up. So a possible "cheat" might be to default to the accidental being on B instead of on the top line (like now). If it has to be given with an xml id, I guess you could look forward to the next nc with pitch=b (though that seems sort of annoyingly circular when we already know where B is!)
An up-down button might still be useful just in case there are weird exceptions (these should be really, really rare; I don't think anybody has seen any in the manuscripts we're working with right now), or in case it's the wrong octave or something. It would also be a workable solution if the @corresp attribute is just too cumbersome to work deal with."

Even if for the moment the flat can't be assigned to a specific neume component, it would be useful just to be able to drag it to where it is on the folio, so that it looks correct visually.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for this issue. Now accid should be able to be anywhere on the staff, and the staff changing action should also function well. Please let us know if anything unexpected happens.

**Comment by JoyfulGen** [comment]
Looks great, thank you!
