### ISSUE TITLE
Feature request: implement divisios minor, maior, and finalis (super not urgent)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#856]
The broader feature request for divisios (https://github.com/DDMAL/Neon/issues/709) was getting long and the most important form for now, the divisio maxima, works perfectly, so I thought I would summarize what's left here. There are three divisio forms that still need to be implemented, as explained by @martha-thomae in this comment:

"The idea is to implement the maxima divisio first (the one covering the whole staff). And later on (this is lower priority) implement the rest: minor, maior, and finalis.
I would leave caesura and virgula as the lowest priority (we haven't found them yet in the manuscripts), so don't worry about these two.
Ich sent this link from LilyPond as a reference on how these different types of divisio look like: https://lilypond.org/doc/v2.23/Documentation/notation/typesetting-gregorian-chant"

This request is extremely non urgent, because there are only maximas in Einsie. I'm just putting this info here for the record!

**Comment by yinanazhou** [comment]
This is a duplicate issue of issue #995. I will close this issue and update there.
