### ISSUE TITLE
"g" toggle for grouping neumes/syllables causes problems with toggled syllables

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#861]
This is my comment from issue https://github.com/DDMAL/Neon/issues/665:

The behaviour with toggled syllables is a bit strange, however. Normally, when selecting a syllable that's toggled with the next one on the staff, the user only gets the option to "Toggle Linked Syllables." Once the syllables are untoggled, selecting one of them gives the option to "Merge" or "Ungroup", as usual. The issue here is that the "g" shortcut allows the user to avoid the "Toggle Linked Syllables" entirely and attempt to ungroup linked syllables. This results in the neume(s) of the second half of the linked syllable to be duplicated on the staff above. This duplicate has the same neume ID, which makes the file invalid and Neon loses its mind. The original second syllable and its duplicate are also toggled with each other. 

Here's the MEI of the first syllable (the duplicate):

<img width="826" alt="253v duplicate" src="https://user-images.githubusercontent.com/83373378/169530435-fdc8da94-1d80-4a20-80b2-3d63e411a2ec.png">

And here's the MEI of the second syllable:

<img width="819" alt="253v OG" src="https://user-images.githubusercontent.com/83373378/169530444-1e559f4f-ff65-4d2b-82d9-e2f68e1bc1bb.png">

I think the ideal solution here is that if the user attempts to ungroup a toggled syllable, the syllables automatically untoggle themselves.

This is the entire MEI file
[253v tfw you're toggled with your clone.mei.zip](https://github.com/DDMAL/Neon/files/8740236/253v.tfw.you.re.toggled.with.your.clone.mei.zip)

_Originally posted by @JoyfulGen in https://github.com/DDMAL/Neon/issues/665#issuecomment-1132862418_

**Comment by yinanazhou** [comment]
@cadagong Can we make the "g" hotkey also work for toggle-linked syllables? If the selected syllables are toggle-linked, we can use "g" to untoggle them. @JoyfulGen would you prefer the untoggling function for toggle-linked syllables using "g"?

**Comment by JoyfulGen** [comment]
I think it could be confusing for the user to have the "g" shortcut both group/ungroup and toggle/untoggle. Maybe the best option could be to just have the "g" shortcut fail if the syllable is toggled. I'm really not sure though... @annamorphism, what do you think?

**Comment by annamorphism** [comment]
Hmm...so if you've selected a group of syllables, g toggles/untoggles them, but if you have a group of neumes (or neume components), g groups/ungroups them? I kind of like it, actually...

**Comment by JoyfulGen** [comment]
Somewhere along the way, this issue got fixed. Now, if the user selects a toggle-linked syllable and presses the "g" toggle, the two syllables become unlinked. To ungroup either one, the user simply has to select them again and press "g" again. This makes sense and works perfectly! Closing issue now.
