### ISSUE TITLE
Divisio behaviour inconsistent when moved vertically on the staff

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#864]
A demonstration:

https://user-images.githubusercontent.com/83373378/172218619-7ee4ac72-22a7-4eb4-a411-76d463fc21d7.mov

When I select the divisio and move it slightly upwards, it immediately jumps to the staff above, even though it's still much closer to the staff it's initially on. But then if I move it back and try to move it up again, it stays on its staff without a fuss. I don't know what makes the difference between the two behaviours, since both occur for the same divisio.

I think the best solution would be to keep the divisio on its initial staff even if its moved up or down, unless the whole thing is fully on another staff.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please provide this mei file? Does it happen very often?

**Comment by JoyfulGen** [comment]
[CH-E_611_251r.mei.zip](https://github.com/DDMAL/Neon/files/8853468/CH-E_611_251r.mei.zip)
This is the file I was working on, but it happens in every folio.

**Comment by yinanazhou** [comment]
Merged first stage fix. One more edge case needs @jinh0 to fix:

When the divLine is a child of a syllable, if the user drags the whole syllable to a new staff line, the divLine remains on the old staff line, whereas all the other elements are dragged to the new staff line.
