### ISSUE TITLE
Require a consult: moving staff sometimes pushes a glyph outside of the facsimile--how to address this?

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#870]
Because of the noise that can happen on the edges of an Einsie folio, there are often many glyphs on the very edge of the page. I've just realized that, if that's the case, moving the staff containing those glyphs can push the left- or rightmost glyph off the page; if this happens on the left side of the image, the `ulx` coordinate of that glyph becomes negative and the file becomes invalid. A demo:

https://user-images.githubusercontent.com/83373378/173589748-140a5086-c5e0-4d3f-b8ba-0df5819ee0af.mov

The problem is that if you don't immediately realize this has happened, the offending glyph is now invisible and therefore impossible to retrieve, unless you move the staff back.

It's actually surprisingly easy to do this without realizing it, which explains the occasional "Invalid ulx" messages we've still been having. But I'm not sure how to address this. What would the best fix be? A notification? Or making it impossible to move a staff beyond its left- and rightmost coordinates? (I like that last fix best, but I'm still very uncertain on how to proceed). @annamorphism, @yinanazhou, what do you think?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I think the latter solution is better. Actually, I think we should limit the position of all the elements and make them only move in the page area. 

Secondly, @cadagong is working on a window that shows the MEI schema log message when clicking the INVALID. This function would also help the user to know where went wrong.

**Comment by fujinaga** [comment]
Don't forget that MEI validation message and log message window are only for developers and testers. We can show these for now but they should normally be hidden for general users (to do later).

**Comment by JoyfulGen** [comment]
This issue is being addressed here https://github.com/DDMAL/Neon/issues/920 so I'll close it.
