### ISSUE TITLE
"Insert to nearest syllable" button doesn't work for all divisios on one staff

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#878]
In Einsie 246r ([246r divisios won't insert.mei.zip](https://github.com/DDMAL/Neon/files/8918953/246r.divisios.won.t.insert.mei.zip)), all the divisios on the 13th staff (third from the bottom) refuse to be inserted to the nearest syllable. Regardless of the selection method (syllable, neume, or neume component), the "Insert to nearest syllable" button hangs and nothing happens. All the other divisios on the page seem to behave normally. I have no idea why this is! I'll update the issue if I find anything else.

**Comment by jinh0** [comment]
Seems to be an issue in Verovio. I'll take a look.

**Comment by jinh0** [comment]
Hey @JoyfulGen , this was an issue with a neume in the 13th staff that didn't have a neume component. Our insertToSyllable() function expected all neumes to have neume components, so it freaked out.

I made a fix for it, and the pull request should be up soon.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. The issue is caused by an empty neume. We have added an empty neume check, but we suggest you first remove empty neumes after loading a file.
