### ISSUE TITLE
Sometimes "Edit" is underlined, but Neon is still in Insert mode

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#892]
When in Insert mode, clicking on one of the edit functions makes "Edit" underlined and brings Neon back to Edit mode. However, if you instead click on the "Edit" banner to collapse it and then click on it again to open it back up, "Edit" is underlined but Neon is still in Insert mode. A demo:

https://user-images.githubusercontent.com/83373378/175029437-caaa1bdb-452f-4825-b7a5-6676578557dd.mov

My suggested solution would be to make it so that collapsing the "Edit" menu does not bring Neon back to Edit mode and therefore "Edit" doesn't become highlighted.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for this issue
