### ISSUE TITLE
Series of actions causes staff to become black while highlighting by staff

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#898]
This is best shown:

https://user-images.githubusercontent.com/83373378/175299408-dbb2635a-3cd5-4f6f-8798-a03c2f968ea4.mov

These are the steps that produce this result:
1. Highlight by staff
2. Turn on bounding boxes
3. Select a staff and change its dimension slightly - it becomes sort of passively selected (not red, but still selected)
4. Turn off bounding boxes

And here's another set of steps that produces the same result:
1. Highlight by neume or syllable
2. Turn on bounding boxes
3. Select a staff and change its dimension slightly
4. Highlight by staff

This is more of a funny quirk than a real problem, but it's still surprising!

**Comment by jinh0** [comment]
The code for highlighting is just straight up messed up. It's confusing, and honestly it's not the first time we've had an issue with unexpected highlighting behavior #830 . It might be time to consider reorganizing the highlighting functionality as a whole.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue.

**Comment by JoyfulGen** [comment]
Now the "passive" selection just doesn't exist! Neat. It was confusing. That definitely fixes all the problems; closing issue now.
