### ISSUE TITLE
Should a user be able to merge a syllable with a syllable that spans two staves?

### ISSUE THREAD

**Issue by cadagong** [DDMAL/Neon#903]
<img width="810" alt="Screen Shot 2022-06-25 at 2 33 21 PM" src="https://user-images.githubusercontent.com/40658078/175786293-ba00e59b-971a-4d23-918b-1273cc0a3d63.png">
 In the example above, should a user be able to merge the syllable circled in blue with the syllable circled in red?

**Comment by cadagong** [comment]
Either way, the behavior on the live site seems to be inconsistent at the moment. If I click on the blue selection first and then the red selection, I am shown the options that include merge (and no option to toggle link). However, if I click on the red selection first and the blue selection second, I am only shown the toggle link option.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I remember we had a discussion about the merging problem of toggle-linked syllables (but I couldn't find which issue it is). 

Currently, the merge option is provided when the user selects a syllable and a toggle-linked syllable. And when the user clicks the merge button, the syllables will not be merged and the toggle-linked syllable will be automatically unlinked. 

What do you think if we just don't provide the merge option for toggle-linked syllables at all?

**Comment by cadagong** [comment]
> Currently, the merge option is provided when the user selects a syllable and a toggle-linked syllable. And when the user clicks the merge button, the syllables will not be merged and the toggle-linked syllable will be automatically unlinked.

@yinanazhou It seems like the option to merge is only provided if the toggle-linked syllable is selected first

**Comment by cadagong** [comment]
> > What do you think if we just don't provide the merge option for toggle-linked syllables at all?
> 
> I think that's best! It's the least confusing, I think, and also avoids problems with the "g" toggle.

So just to clarify: In this case, if the user were to want to merge a multi-stave syllable (a) with a syllable (b) before or after it, the user would first need to toggle (un-link) the lined syllable, merge one of the resulting unlinked syllables (c) with the original syllable (b), and then re-toggle the resulting syllables.

I hope that makes sense!

**Comment by annamorphism** [comment]
> @yinanazhou It seems like the option to merge is only provided if the toggle-linked syllable is selected first

whoa, you're right! somehow never consciously realized this.

**Comment by annamorphism** [comment]
> So just to clarify: In this case, if the user were to want to merge a multi-stave syllable (a) with a syllable (b) before or after it, the user would first need to toggle (un-link) the lined syllable, merge one of the resulting unlinked syllables (c) with the original syllable (b), and then re-toggle the resulting syllables.

this does seem like it would be most consistent with the "g" toggle, as @JoyfulGen says, though I must say it sounds kind of cumbersome. Personally I think I would prefer the other of the two previous behaviours, where you can keep merging new syllables onto an already-linked syllable; otherwise you might have to undo a grouping you just did, group new things, group the stuff you had before...but there is room for disagreement on this.

**Comment by cadagong** [comment]
>Personally I think I would prefer the other of the two previous behaviours, where you can keep merging new syllables onto an already-linked syllable; otherwise you might have to undo a grouping you just did, group new things, group the stuff you had before.

Yes I would agree with this!

**Comment by JoyfulGen** [comment]
Ok sounds good! I guess I've just gotten used to doing it the long way... oops. I agree that Anna's suggestion is much more efficient.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes. You should be able to merge toggle linked syllables now.

**Comment by JoyfulGen** [comment]
Indeed I can! That's very cool. The "g" toggle is even more magical now; you can toggle syllables with it! Fix works perfectly, closing issue now.
