### ISSUE TITLE
Alert user of unsaved changes

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#908]
If the file has been edited but not saved, there should at least be a visual indicator next to the file that there are unsaved changes. Also, we may consider adding a feature where if you try to leave the website with unsaved changes, there should be an alert, like in Google Docs.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. We also added a saved/unsaved indicator beside the file name.

**Comment by JoyfulGen** [comment]
I like that little cloud; it has a lot of personality. I tried adding things and then refreshing the page and I got the alert. Everything works great! Closing issue now.
