### ISSUE TITLE
Master branch doesn't reflect releases

### ISSUE THREAD

**Issue by rettinghaus** [DDMAL/Neon#913]
It is quite strange that the last commit to this repo's default branch happened on [13 Aug 2020](https://github.com/DDMAL/Neon/commit/7f57b0eb6f990b5f7eef3f348a2d1c3389920a44), while the latest release is just three weeks old. 

Also there are so many branches. Why?

**Comment by yinanazhou** [comment]
The master branch has been updated with the latest major release this summer. Branches have also been cleaned up. Closing this issue now.
