### ISSUE TITLE
Update Neon Demo

### ISSUE THREAD

**Issue by rettinghaus** [DDMAL/Neon#914]
It seems like the demo version online is outdated. 
Please update this to the latest version and make it possible to display the current version (e.g. via the local menu).

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please update [Neon demo page](https://github.com/DDMAL/Neon/wiki/Quick-Start) with the videos you made before? Please let me know if you have any questions. Thanks!

**Comment by JoyfulGen** [comment]
Hi @yinanazhou, just to be sure, is it ok if I delete what's already there? Or would you rather I just add my videos at the end?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, what about creating a new demo page and at the end we can add a note where to find the demo for the old version of Neon. In this way, it is less confusing and we don't lost the old demos.

**Comment by yinanazhou** [comment]
The demo version and instructions have already been updated. I will thus close this issue.
