### ISSUE TITLE
Final touches for new index page

### ISSUE THREAD

**Issue by chetbae** [DDMAL/Neon#917]
- [x] Previous index page had:  
_"Neon is developed at [DDMAL](https://ddmal.music.mcgill.ca/) and is part of the [SIMSSA](https://simssa.ca/) project.
Need help? Check out the [Neon quick start guide.](https://github.com/DDMAL/Neon/wiki/Quick-Start)"_, 
implement something similar?
- [x] Sample folios. (limit to 10 CF-??? plus Salzinnes?)
- [x] Style to match editor 💄

**Comment by fujinaga** [comment]
> * [ ]  Previous index page had:
>   _"Neon is developed at [DDMAL](https://ddmal.music.mcgill.ca/) and is part of the [SIMSSA](https://simssa.ca/) project.
>   Need help? Check out the [Neon quick start guide.](https://github.com/DDMAL/Neon/wiki/Quick-Start)"_,
>   implement something similar?

Should be "Neon is developed at [DDMAL Lab](https://ddmal.music.mcgill.ca/)  and is part..."
There should also be a link to to this Github repo.
Also list all the developers that worked on Neon (Neon.js-Legacy-, Neon-index, & Neon_wrapper). Make sure to include Gregory Burlet, who wrote the original code and Andrew Hankinson. Maybe list people in the order of number of commits, after Burlet and Hankinson. 

> * [ ]  Sample folios. (limit to 10 CF-??? plus Salzinnes?)

Yes, just leave as is.
> * [ ]  Style to match editor 💄

Only if this does not take long (e.g., a couple of days of work)
> * [ ]  Hover indicator for pairing components (buttons)

Not sure what this means.

**Comment by chetbae** [comment]
Will do @fujinaga, I'll look into the contribution order and add a footer to Neon.

**Comment by cadagong** [comment]
New landing page and dashboard have been pushed live
