### ISSUE TITLE
Dragging a toggle-linked syllable should only move one part

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#919]
Right now, if you drag a toggle-linked syllable, both parts of the syllable move, which doesn't make sense.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. Please let me know if it works. Thank you!

**Comment by JoyfulGen** [comment]
It looks great! Now, if I drag part of a toggle-linked syllable, only that part moves. Closing issue!
