### ISSUE TITLE
Issue with drag selection calculation

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#927]
Drag selection rectangle does not work as before after PR #911 . Now, you have to have your drag selection rectangle over the entire neume component to select it.

https://user-images.githubusercontent.com/40512164/179577186-432329d4-1870-492c-bd70-16c1ce7bdf7a.mov

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes for this issue. The dragging action should function well now.

**Comment by JoyfulGen** [comment]
It does, thank you!

**Comment by annamorphism** [comment]
can confirm this is fixed!
