### ISSUE TITLE
👻 Out-of-bounds "ghost" clef generated by Verovio

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#933]
Related to #700 .

For some reason, Verovio seems to generate an extra clef in the first staff, which is not reflected in the MEI file, that has coordinates x=0 and some outrageous y-value. What's even weirder is that this y-value varies by folio. One folio has a y-value of 29342 while another has a y-value of 29250. Worth investigating.

![Weird clef](https://user-images.githubusercontent.com/40512164/180112694-b04d62f6-9e9d-406e-9651-2081d58e266a.png)

**Comment by annamorphism** [comment]
Weird. I'm not sure how to see what you're seeing... I could see the mystery coordinate being dependent on the height of the page (but shouldn't they all be the same?). If not, maybe there's some relationship to where the first staff actually is? Definitely very strange.
