### ISSUE TITLE
Neon won't allow you to regroup neumes within the same syllable

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#938]
If I ungroup a neume, I get the notification that the ungrouping was a success. However, if I try to regroup some or all of those neume components using the neume selector, the operation fails. Demo:

https://user-images.githubusercontent.com/83373378/180820344-93d362e8-5eb8-48ed-9aaf-10f6e62baa30.mov

I understand that this happens because if neumes are part of the same syllable, they're technically already grouped, even if you've just ungrouped them. In other words, grouping previously grouped neumes isn't actually breaking anything, it's just redundant. @yinanazhou, did I understand that correctly? If so, the ideal fix here would be to just allow the user to group neumes if they want to, even if it's not necessary. And if the user is savvy, they can skip that and jump to the neume component selector directly. Does that make sense?

**Comment by annamorphism** [comment]
@JoyfulGen I'm not sure we want to allow more groupings--for example, we don't want to end up with a situation where those last three puncta are grouped into a syllable sitting inside a syllable. i have a weird feeling that letting people group this way would create all sorts of funny business, but I could be wrong. 
HOWEVER at the very least I do think the error message could be changed, so that instead of just telling you it failed, it says e.g. "These neumes are already grouped!" which would avoid some frustration on the part of the user. 

Tbh this aspect of ungrouping at one level and re-grouping at another is probably one of the more confusing things when I was learning it. I wonder if there is some way of making it more obvious/intuitive...

**Comment by yinanazhou** [comment]
Hi @annamorphism and @JoyfulGen, sorry for the late reply. One thing we could do is not to give the user the option to group neumes within a syllable. I have pushed the changes for the option fix (only give the options that are eligible to the user) in PR #904. Please let @cadagong and me know if anything unexpected happens.

**Comment by JoyfulGen** [comment]
> p.s. @JoyfulGen what's the reason why so many of the stems in your video have floated off their obliques...?

Oh, that's just an old mistake of mine that popped back up here because I used rodan production instead of staging... No worries, this isn't an issue anymore.

**Comment by JoyfulGen** [comment]
> Hi @annamorphism and @JoyfulGen, sorry for the late reply. One thing we could do is not to give the user the option to group neumes within a syllable. I have pushed the changes for the option fix (only give the options that are eligible to the user) in PR #904. Please let @cadagong and me know if anything unexpected happens.

@yinanazhou, Anna and I discussed this and we find this ultimately more confusing than it used to be. The problem is that, depending on the situation, the user sometimes has to group neumes and then neume components, and sometimes just neume components. It used to be that when you selected two neumes within one syllable, you could group them; nothing would happen from a code perspective, but nothing bad would happen either. So it would _feel_ like the steps required to group neumes were consistent. Would it be possible to get it back to that?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, just to be clear, the expected behaviour of grouping two neumes within one syllable is to make them a bigger neume? Should users have the option to group neumes in different syllables?

**Comment by JoyfulGen** [comment]
@yinanazhou I just stumbled unto this while looking for something else and I think this discussion has been resolved now? Can the issue be closed?
