### ISSUE TITLE
Selected syllables don't get highlighted when in the Neume Highlight

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#944]
If I'm using the overall Neume Highlight option and I use the syllable selection tool, elements I click on don't get highlighted. If I go to the Syllable Highlight option I can see that the element I clicked on really is selected; it's just not showing up when highlighting by neume. Here's the demo:

https://user-images.githubusercontent.com/83373378/182158340-6ddd52c4-7008-4c43-9960-8274e0be58a4.mov

I tried all the other combos I could think of (selecting a staff when highlighting by syllable, for example) and everything else always becomes highlighted if you select it. It's only selecting syllables when highlighting by neume that's not working right now.

**Comment by annamorphism** [comment]
@JoyfulGen your movie didn't upload...

**Comment by JoyfulGen** [comment]
Should be there now! Took me three tries, but we made it in the end.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. Please let me know if it works. Thanks!

**Comment by JoyfulGen** [comment]
Fixed! Syllables are always highlighted now. Thank you! Closing issue.
