### ISSUE TITLE
Custodes not behaving - jump around after being edited

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#952]
From what I can tell, if I move a custos anywhere on the page from its original position, it initially stays there, but as soon as I do any other action it jumps back to where it was. Demo:

https://user-images.githubusercontent.com/83373378/183478391-431e7703-dcd4-4610-80cf-eeba2ca61098.mov

In the MEI, the pitch of the custos never changes, so my moving it isn't registered at all. The behaviour is the same for straight-outta-omr custodes and custodes I've inserted myself. 

I'm also noticing that the custodes are also not "locking in" to a position when I put them somewhere. It used to be that wherever I moved a custos, it would sort of stabilize at the nearest staff line or space, but now it stays exactly where I put it, so the pitch is less clearly defined. Could these two behaviours be connected?

**Comment by annamorphism** [comment]
@JoyfulGen it sounds to me like the custodes are behaving sort of like accidentals in terms of their free motion on the page, but then regress back to working like a neume component with a pitch as soon as the MEI is re-evaluated. We don't actually want/need them to be able to move around like accidentals--more like clefs...

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes to GitHub pages. Please let me know if it works properly now. Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou it looks great! Custodes now snick in to the nearest staff line/space when I move them and stay there. Thank you :) Closing issue now.
