### ISSUE TITLE
No glyphs in viewer, MEI status says "No MEI"

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#958]
Folio 105r has no glyphs at all and the MEI status says "No MEI." 
<img width="1440" alt="105r no MEI" src="https://user-images.githubusercontent.com/83373378/184166284-c92c2143-16fc-4318-af8e-faa0ea995ae9.png">

Two additional things:
1. I'm positive I worked on that folio and saved my work, so there was definitely MEI on there at first. Also, if I re-upload the file, the MEI's there. (This is the file in question: [105r.mei.zip](https://github.com/DDMAL/Neon/files/9309747/105r.mei.zip))
2. Folio 105v is being identified as 105r. It says 105v in the Index menu and in the search bar, but 105r in the Neon viewer. 
<img width="1440" alt="105v misabelled" src="https://user-images.githubusercontent.com/83373378/184167663-04924c1e-6efa-49bf-82db-93c06d58c03d.png">

The same mislabelling thing happened for the other folio that lost its MEI, so I'm guessing the two things are connected. I haven't found the series of actions that causes this yet, but I'll keep looking!

@chetbae I'm told this is a mission for you

**Comment by chetbae** [comment]
I started looking some dashboard issues yesterday @JoyfulGen, this one is funky! It's almost certainly due to something files getting mixed up during upload/pairing time - fix incoming.

**Comment by annamorphism** [comment]
I was getting a very similar problem in #947 --probably the same thing described differently.

**Comment by chetbae** [comment]
Sorry this took so long! Elusive but I tracked the error down to being Neon making a shallow copy of the template manifest instead of a deep copy. So whenever there were multiple uploads, the asynchronous uploads were overwriting each other. 

This should only be for any uploads made after the dashboard was introduced, if any folios were **renamed** from before, please let me know! @annamorphism @JoyfulGen.

**Comment by chetbae** [comment]
Also with the new fixes, we decided to make the decision to strip the _.mei_ extension when uploading a folio for the name, so don't be alarmed!

**Comment by yinanazhou** [comment]
Hi @annamorphism @JoyfulGen, has this issue been resolved?

**Comment by JoyfulGen** [comment]
Oh, yes it has! I meant to update this page and must've gotten sidetracked, I'm sorry. Closing issue now.
