### ISSUE TITLE
Can't move staff if it has no neumes on it

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#978]
If a staff on Neon is empty, moving it triggers the Out-of-bounds notification and snaps it back, even if it's not out of bounds at all. I can however resize the staff to anywhere within the page. If I add any glyph to that staff, I can move it without any problem. Demonstration:

https://user-images.githubusercontent.com/83373378/198295138-60e00fbe-8e04-4be6-94af-6665d10eec68.mov

This appears to be true of any MEI file I try, including the sample documents provided in Neon. I can still move empty staves around by resizing them, but it'd be great to be able to move them with the usual click-and-drag.

**Comment by yinanazhou** [comment]
This issue is caused by staff selection. Now we can only really "select" a staff when clicking on an element on the staff. When we click on the other parts of a staff, the staff gets highlighted, but it is not really selected. This issue will be solved together with task 1 in issue #940.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. Could you please check it? Thanks!

**Comment by JoyfulGen** [comment]
Fixed! Closing issue now.
